/* ============================================================================
 FILE:         INV_to_GL_Interface.sql
 INTERFACE:    IF-03: Legacy Oracle INV (Inventory / Cost Management)
 --> New Oracle GL (Journal Import)
 VERSION:      1.0
 PLATFORM:     Oracle EBS R12.2 (Legacy) --> Oracle EBS R12.2 (New Instance)
 
 DESCRIPTION:
 ------------
 Extracts inventory accounting entries generated by material transactions
 in the legacy Oracle Inventory and Cost Management modules and loads them
 into the new Oracle GL via the GL_INTERFACE open interface table.
 
 The standard Oracle Journal Import program (Source: XXCUST_INV_ACCT)
 completes journal creation in the new GL instance after each interface run.
 
 CORE BUSINESS RULE:
 Only material transactions that have generated accounting entries in
 MTL_TRANSACTION_ACCOUNTS AND whose accounting_date falls within an open
 or future-enterable GL period in the new instance will be interfaced.
 
 IN-SCOPE TRANSACTION TYPES (MTL_MATERIAL_TRANSACTIONS.transaction_type_id):
 ─────────────────────────────────────────────────────────────────────────────
 1   Purchase Order Receipt (into Receiving Inspection)
 2   Subinventory Transfer
 3   Direct Inter-Organisation Transfer
 4   Cycle Count Adjustment / Physical Inventory Adjustment / Misc Adjustment
 5   Miscellaneous Issue / Receipt
 17  PO Deliver to Subinventory  /  RMA Receipt to Stock
 21  Intransit Shipment (Inter-Org)
 22  Intransit Receipt (Inter-Org)
 24  Standard Cost Update
 27  Receipt into Inspection (Return PO)
 33  Sales Order Issue (COGS)
 34  Account Alias Issue
 35  WIP Component Issue
 44  WIP Assembly Completion
 
 JOURNAL CATEGORIES (registered in new GL, source: XXCUST_INV_ACCT):
 ─────────────────────────────────────────────────────────────────────────────
 Receiving           -- Types 1, 17 (PO receipt stages)
 Inventory           -- Types 2, 3, 21, 22
 Cost of Goods Sold  -- Types 33 (Sales Order Issues)
 Inventory Accounting-- Types 4, 5, 24, 27, 34 (Adjustments, Misc, Std Cost)
 WIP                 -- Types 35, 44
 
 SOURCE TABLES (LEGACY INSTANCE -- accessed via DB Link: LEGACY_INSTANCE):
 ─────────────────────────────────────────────────────────────────────────────
 MTL_MATERIAL_TRANSACTIONS      Transaction header (type, date, org, item)
 MTL_TRANSACTION_ACCOUNTS       Accounting lines (CCID, signed amount)
 MTL_SYSTEM_ITEMS_B             Item master (description, UOM)
 MTL_PARAMETERS                 Org costing method
 CST_COST_GROUPS                Cost group master (Average Cost orgs)
 GL_CODE_COMBINATIONS           Legacy COA (concatenated segment string)
 GL_PERIODS                     Legacy GL period calendar
 HR_ORGANIZATION_UNITS          Organisation name
 PO_HEADERS_ALL                 PO number (for receipt transactions)
 OE_ORDER_HEADERS_ALL           Sales Order number (for SO issue transactions)
 WIP_DISCRETE_JOBS              WIP job number (for WIP transactions)
 
 TARGET TABLES (NEW INSTANCE):
 ─────────────────────────────────────────────────────────────────────────────
 GL_INTERFACE                   Standard Oracle GL open interface table
 GL_JE_BATCHES                  Queried post-import (confirmation)
 GL_JE_HEADERS                  Queried post-import (confirmation)
 GL_JE_LINES                    Queried post-import (reconciliation)
 XXCUST_INV_GL_INTERFACE_LOG    Custom control and audit log
 XXCUST_COA_MAPPING             Legacy CCID --> New CCID mapping (shared)
 
 PREREQUISITES:
 ─────────────────────────────────────────────────────────────────────────────
 1.  DB link LEGACY_INSTANCE created with SELECT grants on all source tables
 2.  GL source XXCUST_INV_ACCT registered in new GL
 3.  Journal categories registered: Receiving, Inventory, Cost of Goods Sold,
 Inventory Accounting, WIP
 4.  XXCUST_COA_MAPPING populated for all inventory account CCIDs
 (Inventory Valuation, Receiving Inspection, AP Accrual, COGS, Intransit,
 WIP Valuation, Adjustment/Variance accounts for all orgs in scope)
 5.  GL period(s) open in new instance for the transaction date range
 6.  Best practice: inventory accounting period closed in legacy instance
 before running to capture all cost adjustments for the period
 7.  XXCUST_INV_GL_INTERFACE_LOG DDL executed (Section 1)
 8.  XXCUST_INV_GL_INTERFACE_PKG compiled (Sections 2-3)
 
 TABLE OF CONTENTS:
 ─────────────────────────────────────────────────────────────────────────────
 SECTION 1  : DDL -- XXCUST_INV_GL_INTERFACE_LOG (Control / Audit Log)
 SECTION 2  : Package Specification -- XXCUST_INV_GL_INTERFACE_PKG
 SECTION 3  : Package Body
 3A: Private utilities (log_msg, get_new_ccid, get_period_name,
 get_sob_id, get_je_category, get_source_doc_ref,
 validate_transaction, load_gl_line)
 3B: run_interface -- main processing procedure
 Cursor: c_inv_accounting (MTL_TRANSACTION_ACCOUNTS)
 Processing loop with E-V-T-L pattern
 3C: purge_log
 SECTION 4  : Reconciliation Queries
 4A: MTL accounting lines vs interface log
 4B: GL_INTERFACE vs GL_JE_LINES (post-import)
 4C: Journal balance check (DR = CR per group_id)
 4D: Inventory valuation amount reconciliation
 SECTION 5  : Execution Guide
 
 CHANGE LOG:
 ─────────────────────────────────────────────────────────────────────────────
 v1.0   Initial release
 ============================================================================ */
/* ============================================================================
 SECTION 1: DDL -- XXCUST_INV_GL_INTERFACE_LOG
 ============================================================================ */
CREATE TABLE xxcust_inv_gl_interface_log (
    log_id                  NUMBER
        GENERATED ALWAYS AS IDENTITY
        CONSTRAINT xxcust_inv_gl_log_pk PRIMARY KEY,
    -- Run identification
    run_id                  VARCHAR2(50) NOT NULL,
    run_date                DATE DEFAULT sysdate,
    -- Source transaction details (from legacy MTL tables)
    journal_category        VARCHAR2(50),
    -- GL journal category assigned
    legacy_mtl_txn_id       NUMBER,
    -- MTL_MATERIAL_TRANSACTIONS.transaction_id
    legacy_txn_type_id      NUMBER,
    -- MTL_MATERIAL_TRANSACTIONS.transaction_type_id
    legacy_org_id           NUMBER,
    -- Inventory organisation ID
    legacy_org_name         VARCHAR2(240),
    -- Organisation name (for readability)
    legacy_item_id          NUMBER,
    -- MTL_MATERIAL_TRANSACTIONS.inventory_item_id
    legacy_item_description VARCHAR2(240),
    -- Item description
    -- Accounting line details
    legacy_ccid             NUMBER,
    -- MTL_TRANSACTION_ACCOUNTS.reference_account (legacy)
    legacy_account_num      VARCHAR2(240),
    -- Concatenated legacy account string (for audit)
    new_ccid                NUMBER,
    -- XXCUST_COA_MAPPING.new_ccid (new instance)
    accounting_date         DATE,
    -- MTL_MATERIAL_TRANSACTIONS.transaction_date
    period_name             VARCHAR2(15),
    -- Derived GL period in new instance
    currency_code           VARCHAR2(15),
    entered_dr              NUMBER,
    entered_cr              NUMBER,
    accounted_dr            NUMBER,
    accounted_cr            NUMBER,
    -- Source document reference (PO, SO, WIP job, etc.)
    source_doc_reference    VARCHAR2(100),
    -- GL interface tracking
    gl_interface_group_id   NUMBER,
    -- group_id used for Journal Import
    je_batch_name           VARCHAR2(100),
    -- populated after Journal Import
    -- Status and error tracking
    interface_status        VARCHAR2(20),
    -- PROCESSED, REJECTED, ERROR
    rejection_reason        VARCHAR2(2000),
    -- Audit columns
    created_by              NUMBER DEFAULT - 1,
    creation_date           DATE DEFAULT sysdate,
    last_updated_by         NUMBER DEFAULT - 1,
    last_update_date        DATE DEFAULT sysdate
);
-- Indexes for common access patterns
CREATE INDEX xxcust_inv_gl_log_n1 ON
    xxcust_inv_gl_interface_log (
        run_id
    );

CREATE INDEX xxcust_inv_gl_log_n2 ON
    xxcust_inv_gl_interface_log (
        legacy_mtl_txn_id
    );

CREATE INDEX xxcust_inv_gl_log_n3 ON
    xxcust_inv_gl_interface_log (
        interface_status
    );

CREATE INDEX xxcust_inv_gl_log_n4 ON
    xxcust_inv_gl_interface_log (
        period_name
    );

CREATE INDEX xxcust_inv_gl_log_n5 ON
    xxcust_inv_gl_interface_log (
        accounting_date
    );

CREATE INDEX xxcust_inv_gl_log_n6 ON
    xxcust_inv_gl_interface_log (
        legacy_txn_type_id
    );

CREATE INDEX xxcust_inv_gl_log_n7 ON
    xxcust_inv_gl_interface_log (
        legacy_org_id
    );
/* ============================================================================
 SECTION 2: PACKAGE SPECIFICATION -- XXCUST_INV_GL_INTERFACE_PKG
 ============================================================================ */
CREATE OR REPLACE PACKAGE xxcust_inv_gl_interface_pkg AS
    /*
     || IF-03: Legacy Oracle Inventory --> New Oracle GL Journal Import Interface
     ||
     || Extracts MTL_TRANSACTION_ACCOUNTS entries for in-scope inventory
     || transaction types from the legacy instance via DB link and loads
     || them into GL_INTERFACE in the new instance.
     ||
     || Transaction types covered:
     ||   PO Receipts (1, 17, 27), Transfers (2, 3, 21, 22),
     ||   SO Issues (33, 34), Adjustments (4, 5, 24),
     ||   WIP (35, 44)
     ||
     || Call run_interface() then run standard Journal Import in new GL:
     ||   Source   : XXCUST_INV_ACCT
     ||   Group ID : returned in p_group_id OUT parameter
     */
    -- -------------------------------------------------------------------------
    -- Main interface procedure.
    -- Extracts inventory accounting lines and loads to GL_INTERFACE.
    -- Returns the group_id to use when running Journal Import.
    -- -------------------------------------------------------------------------
    PROCEDURE run_interface (
        p_errbuf          OUT VARCHAR2,
        p_retcode         OUT NUMBER,
        p_group_id        OUT NUMBER,
        -- group_id for Journal Import
        p_organization_id IN NUMBER DEFAULT NULL,
        -- NULL = all orgs
        p_txn_date_from   IN VARCHAR2 DEFAULT NULL,
        -- DD-MON-YYYY
        p_txn_date_to     IN VARCHAR2 DEFAULT NULL,
        -- DD-MON-YYYY
        p_txn_type_ids    IN VARCHAR2 DEFAULT NULL,
        -- CSV list e.g. '1,17,33'
        -- NULL = all in-scope types
        p_debug_mode      IN VARCHAR2 DEFAULT 'N'
    );
-- -------------------------------------------------------------------------
-- Purge processed log records older than N days.
-- -------------------------------------------------------------------------
    PROCEDURE purge_log (
        p_days_to_keep IN NUMBER DEFAULT 90
    );

END xxcust_inv_gl_interface_pkg;
/
/* ============================================================================
 SECTION 3: PACKAGE BODY -- XXCUST_INV_GL_INTERFACE_PKG
 ============================================================================ */
CREATE OR REPLACE PACKAGE BODY xxcust_inv_gl_interface_pkg AS -- =========================================================================
    -- 3A: CONSTANTS
    -- =========================================================================
    -- GL Journal Source registered in new instance
    c_gl_source            CONSTANT VARCHAR2(50) := 'XXCUST_INV_ACCT';
-- Interface run prefix
    c_run_prefix           CONSTANT VARCHAR2(10) := 'INV-';
-- Actual flag (A = Actual; B = Budget; E = Encumbrance)
    c_actual_flag          CONSTANT VARCHAR2(1) := 'A';
-- Created_by placeholder -- replace with FND_GLOBAL.USER_ID in production
    c_created_by           CONSTANT NUMBER := -1;
-- Chart of accounts ID for new GL instance
    c_chart_of_accounts_id CONSTANT NUMBER := 50428;
-- Status constants
    c_status_processed     CONSTANT VARCHAR2(20) := 'PROCESSED';
    c_status_rejected      CONSTANT VARCHAR2(20) := 'REJECTED';
    c_status_error         CONSTANT VARCHAR2(20) := 'ERROR';
-- -------------------------------------------------------------------------
-- In-scope transaction type IDs.
-- This collection is used to build the dynamic IN list for the main cursor
-- when no specific p_txn_type_ids parameter is supplied.
-- -------------------------------------------------------------------------
    TYPE t_txn_type_tab IS
        TABLE OF NUMBER INDEX BY PLS_INTEGER;
-- All in-scope inventory transaction types (see file header for descriptions)
    g_all_txn_types        t_txn_type_tab;
-- -------------------------------------------------------------------------
-- Journal category mapping by transaction type.
-- Populated in package initialisation block.
-- -------------------------------------------------------------------------
    TYPE t_category_map IS
        TABLE OF VARCHAR2(50) INDEX BY PLS_INTEGER;
    g_category_map         t_category_map;
-- =========================================================================
-- 3A: PRIVATE UTILITIES
-- =========================================================================
-- -------------------------------------------------------------------------
-- Write a timestamped message to DBMS_OUTPUT.
-- In a full EBS concurrent program, replace with:
--   FND_FILE.PUT_LINE(FND_FILE.LOG, p_msg);
-- -------------------------------------------------------------------------
    PROCEDURE log_msg (
        p_msg IN VARCHAR2
    ) IS
    BEGIN
        dbms_output.put_line(to_char(sysdate, 'DD-MON-YYYY HH24:MI:SS')
                             || ' | '
                             || p_msg);
    END log_msg;
-- -------------------------------------------------------------------------
-- Lookup new COA CCID from XXCUST_COA_MAPPING.
-- Returns -1 if no active mapping is found.
-- -------------------------------------------------------------------------
---------------------------------------------------------------------------
-- Helper functions to get segment values for COA mapping (if needed in transformation logic)
---------------------------------------------------------------------------
    FUNCTION get_division_segment (
        p_org_id IN NUMBER
    ) RETURN VARCHAR2 IS
        l_division_segment VARCHAR2(25);
    BEGIN
        SELECT
            division_code
        INTO l_division_segment
        FROM
            apps.mapping_division_segment
        WHERE
            organization_id = p_org_id;

        log_msg('Division segment mapping: org_id='
                || p_org_id
                || ' → division_segment='
                || l_division_segment);
        RETURN l_division_segment;
    EXCEPTION
        WHEN OTHERS THEN
            log_msg('Division segment mapping: org_id='
                    || p_org_id
                    || ' → division_segment=01 (default, no mapping found)');
            RETURN '01';
    END get_division_segment;
---------------------------------------------------------------------------
-- Helper function to get product segment for an item (if needed in transformation logic)
---------------------------------------------------------------------------
    FUNCTION get_product_segment (
        item_id IN NUMBER
    ) RETURN VARCHAR2 IS
        l_product_code VARCHAR2(50);
    BEGIN
        SELECT
            product_code
        INTO l_product_code
        FROM
            apps.mapping_product_segment
        WHERE
            inventory_item_id = item_id;

        log_msg('Product segment mapping: item_id='
                || item_id
                || ' → product_code='
                || l_product_code);
        RETURN l_product_code;
    EXCEPTION
        WHEN no_data_found THEN
            log_msg('Product segment mapping: item_id='
                    || item_id
                    || ' → product_code=00000000 (default, no mapping found)');
            RETURN '00000000';
    END get_product_segment;
-----------------------------------------------------------------------------
-- Helper function to determine transaction type segment for tax code
-----------------------------------------------------------------------------
    FUNCTION get_txn_type_segment (
        p_rcv_transaction_id IN NUMBER
    ) RETURN VARCHAR2 IS
        l_tax_code VARCHAR2(100);
    BEGIN -- Get the first tax_rate_code from JAI_TAX_LINES_ALL for this receipt transaction
        SELECT
            lower(jtl.tax_rate_code)
        INTO l_tax_code
        FROM
            apps.jai_tax_lines_all@legacy_instance jtl
        WHERE
                jtl.trx_id = p_rcv_transaction_id
            AND ROWNUM = 1;

        IF l_tax_code LIKE 'cgst%'
           OR l_tax_code LIKE 'sgst%' THEN
            RETURN '1';
-- LOCAL SALE
        ELSIF l_tax_code LIKE 'igst%' THEN
            RETURN '2';
-- INTERSTATE
        ELSE
            RETURN '0';
-- DEFAULT
        END IF;

    EXCEPTION
        WHEN no_data_found THEN
            RETURN '0';
-- DEFAULT (no tax lines found)
        WHEN OTHERS THEN
            RETURN '0';
    END get_txn_type_segment;
-------------------------------------------------------------------------
-- Helper function to get department segment value based on old flex value
--------------------------------------------------------------------------
    FUNCTION get_department_segment (
        old_flex_value IN NUMBER
    ) RETURN VARCHAR2 IS
        l_new_segment VARCHAR2(25);
    BEGIN
        SELECT
            new_department_flex_value
        INTO l_new_segment
        FROM
            apps.mapping_department_segment
        WHERE
            old_department_flex_value = old_flex_value;

        log_msg('Department segment mapping: old_flex_value='
                || old_flex_value
                || ' → new_segment='
                || l_new_segment);
        RETURN l_new_segment;
    EXCEPTION
        WHEN OTHERS THEN
            log_msg('Department segment mapping: old_flex_value='
                    || old_flex_value
                    || ' → new_segment=BAD07 (default, no mapping found)');
            RETURN '00000';
    END get_department_segment;
-------------------------------------------------------------------------
-- Helper function to get  ACCOUNT segment value based on old flex value
--------------------------------------------------------------------------
    FUNCTION get_account_segment (
        old_flex_value IN NUMBER
    ) RETURN VARCHAR2 IS
        l_new_segment VARCHAR2(6);
    BEGIN
        SELECT
            to_char(new_account_flex_value)
        INTO l_new_segment
        FROM
            apps.mapping_account_segment
        WHERE
            old_account_flex_value = old_flex_value;
-- Treat 0 as unmapped (column is NUMBER(6), so missing mappings may store 0)
        IF l_new_segment IS NULL
           OR l_new_segment = '0' THEN
            log_msg('Account segment mapping: old_flex_value='
                    || old_flex_value
                    || ' → new_segment='
                    || l_new_segment
                    || ' (treated as unmapped)');
            RETURN NULL;
        END IF;

        log_msg('Account segment mapping: old_flex_value='
                || old_flex_value
                || ' → new_segment='
                || l_new_segment);
        RETURN l_new_segment;
    EXCEPTION
        WHEN no_data_found THEN
            log_msg('Account segment mapping: old_flex_value='
                    || old_flex_value
                    || ' → no row found (returning NULL)');
            RETURN NULL;
        WHEN OTHERS THEN
            log_msg('Account segment mapping: old_flex_value='
                    || old_flex_value
                    || ' → error: '
                    || sqlerrm
                    || ' (returning NULL)');
            RETURN NULL;
    END get_account_segment;
-------------------------------------------------------------------------
-- Fallback: Derive account segment from item when old account has no mapping.
-- Resolution: 1) Product prefix → account  2) Item description keywords → account
--             3) Default 513001 (General Consumables)
-------------------------------------------------------------------------
    FUNCTION get_account_segment_fallback (
        p_inventory_item_id IN NUMBER
    ) RETURN VARCHAR2 IS

        l_new_segment    VARCHAR2(6);
        l_product_code   VARCHAR2(8);
        l_product_prefix VARCHAR2(4);
        l_item_desc      VARCHAR2(240);
    BEGIN
        log_msg('Account fallback: starting for item_id=' || p_inventory_item_id);
-- Step 1: Try product prefix mapping (item already in MAPPING_PRODUCT_SEGMENT)
        BEGIN
            SELECT
                ps.product_code
            INTO l_product_code
            FROM
                apps.mapping_product_segment ps
            WHERE
                ps.inventory_item_id = p_inventory_item_id;

            l_product_prefix := substr(l_product_code, 1, 2);
            log_msg('Account fallback Step 1: item_id='
                    || p_inventory_item_id
                    || ' → product_code='
                    || l_product_code
                    || ' → prefix='
                    || l_product_prefix);

            SELECT
                to_char(ppa.new_account_flex_value)
            INTO l_new_segment
            FROM
                apps.mapping_product_prefix_account ppa
            WHERE
                ppa.product_prefix = l_product_prefix;

            log_msg('Account fallback Step 1: prefix='
                    || l_product_prefix
                    || ' → account='
                    || l_new_segment);
            RETURN l_new_segment;
        EXCEPTION
            WHEN no_data_found THEN
                log_msg('Account fallback Step 1: no mapping found, falling through to keyword matching');
                NULL;
-- fall through to keyword matching
        END;
-- Step 2: Try keyword matching on item description
        BEGIN
            SELECT
                description
            INTO l_item_desc
            FROM
                apps.mtl_system_items_b@legacy_instance
            WHERE
                    inventory_item_id = p_inventory_item_id
                AND ROWNUM = 1;

            log_msg('Account fallback Step 2: item_id='
                    || p_inventory_item_id
                    || ' → description='
                    || substr(l_item_desc, 1, 100));

        EXCEPTION
            WHEN no_data_found THEN
                log_msg('Account fallback Step 2: no item description found, returning default 513001');
                RETURN '513001';
-- default
        END;

        BEGIN
            SELECT
                to_char(ka.new_account_flex_value)
            INTO l_new_segment
            FROM
                (
                    SELECT
                        ka.new_account_flex_value
                    FROM
                        apps.mapping_item_keyword_account ka
                    WHERE
                        upper(l_item_desc) LIKE upper(ka.keyword_pattern)
                    ORDER BY
                        ka.priority ASC
                ) ka
            WHERE
                ROWNUM = 1;

            log_msg('Account fallback Step 2: keyword match → account=' || l_new_segment);
            RETURN l_new_segment;
        EXCEPTION
            WHEN no_data_found THEN
                log_msg('Account fallback Step 2: no keyword match, returning default 513001');
                RETURN '513001';
-- default: General Consumables
        END;

    EXCEPTION
        WHEN OTHERS THEN
            log_msg('Account fallback: unexpected error: '
                    || sqlerrm
                    || ', returning default 513001');
            RETURN '513001';
    END get_account_segment_fallback;
-------------------------------------------------------------------------
-- Derive new ccid based on legacy ccid and mapping table.
-------------------------------------------------------------------------
    FUNCTION derive_new_ccid (
        p_legacy_ccid          IN NUMBER,
        p_inventory_org_id     IN NUMBER,
        p_inventory_item_id    IN NUMBER,
        p_rcv_transaction_id   IN NUMBER,
        p_chart_of_accounts_id IN NUMBER DEFAULT c_chart_of_accounts_id
    ) RETURN NUMBER IS -- Old segments from legacy GL_CODE_COMBINATIONS
        l_old_seg2        VARCHAR2(25);
-- COSTCENTER → maps to DEPARTMENT
        l_old_seg4        VARCHAR2(25);
-- ACCOUNT    → maps to ACCOUNT
-- New segments
        l_seg1_entity     VARCHAR2(25) := '01';
-- fixed
        l_seg2_division   VARCHAR2(25);
        l_seg3_account    VARCHAR2(25);
        l_seg4_department VARCHAR2(25);
        l_seg5_product    VARCHAR2(25);
        l_seg6_txn_type   VARCHAR2(25);
        l_seg7_future1    VARCHAR2(25) := '000';
-- fixed
        l_seg8_future2    VARCHAR2(25) := '000';
-- fixed
        l_new_ccid        NUMBER;
    BEGIN -- Step 1: Get only the segments we need from legacy CCID
        SELECT
            gcc.segment2,
            gcc.segment4
        INTO
            l_old_seg2,
            l_old_seg4
        FROM
            apps.gl_code_combinations@legacy_instance gcc
        WHERE
            gcc.code_combination_id = p_legacy_ccid;
-- Step 2: Derive each new segment
        l_seg2_division := get_division_segment(p_inventory_org_id);
        l_seg3_account := get_account_segment(TO_NUMBER(l_old_seg4));
-- Fallback: if old account has no mapping, derive from item
        IF l_seg3_account IS NULL THEN
            l_seg3_account := get_account_segment_fallback(p_inventory_item_id);
            log_msg('  Account fallback used for item_id='
                    || p_inventory_item_id
                    || ' → account='
                    || l_seg3_account);
        END IF;

        l_seg4_department := get_department_segment(TO_NUMBER(l_old_seg2));
        l_seg5_product := get_product_segment(p_inventory_item_id);
-- uses item_id directly
        l_seg6_txn_type := get_txn_type_segment(p_rcv_transaction_id);
-- LOG EACH DERIVED NEW SEGMENTS
        log_msg('Derived segments for legacy CCID '
                || p_legacy_ccid
                || ':');
        log_msg('  Division segment: ' || l_seg2_division);
        log_msg('  Account segment: ' || l_seg3_account);
        log_msg('  Department segment: ' || l_seg4_department);
        log_msg('  Product segment: ' || l_seg5_product);
        log_msg('  Transaction type segment: ' || l_seg6_txn_type);
-- Step 3: Look up new CCID from GL_CODE_COMBINATIONS in new instance
        BEGIN
            SELECT
                gcc.code_combination_id
            INTO l_new_ccid
            FROM
                gl_code_combinations gcc
            WHERE
                    gcc.chart_of_accounts_id = p_chart_of_accounts_id
                AND gcc.segment1 = l_seg1_entity
                AND gcc.segment2 = l_seg2_division
                AND gcc.segment3 = l_seg3_account
                AND gcc.segment4 = l_seg4_department
                AND gcc.segment5 = l_seg5_product
                AND gcc.segment6 = l_seg6_txn_type
                AND gcc.segment7 = l_seg7_future1
                AND gcc.segment8 = l_seg8_future2
                AND gcc.enabled_flag = 'Y';

            RETURN l_new_ccid;
        EXCEPTION
            WHEN no_data_found THEN
                log_msg('CCID not found for segments '
                            || l_seg1_entity || '.' || l_seg2_division || '.'
                            || l_seg3_account || '.' || l_seg4_department || '.'
                            || l_seg5_product || '.' || l_seg6_txn_type || '.'
                            || l_seg7_future1 || '.' || l_seg8_future2
                            || ' — no matching CCID in GL_CODE_COMBINATIONS. Add the account combination.');
                RETURN -1;
        END;

    EXCEPTION
        WHEN OTHERS THEN
            log_msg('derive_new_ccid FATAL: legacy_ccid='
                    || p_legacy_ccid
                    || ' error='
                    || sqlerrm);
            RETURN -1;
    END derive_new_ccid;
-- -------------------------------------------------------------------------
-- Derive the GL period_name in the new instance for a given date.
-- Looks up an Open or Future-Enterable period in the new GL calendar.
-- Returns NULL if no matching open period exists (triggers BR-06 rejection).
-- -------------------------------------------------------------------------
    FUNCTION get_period_name (
        p_accounting_date IN DATE
    ) RETURN VARCHAR2 IS
        l_period_name VARCHAR2(15);
    BEGIN
        SELECT 
            gps.period_name
        INTO   l_period_name
        FROM   
                apps.gl_period_statuses       gps
            JOIN   apps.ar_system_parameters_all asp ON asp.set_of_books_id = gps.set_of_books_id
        WHERE  
            gps.start_date              <= p_accounting_date
            AND    gps.end_date                >= p_accounting_date
            AND    (gps.closing_status = 'O' OR gps.closing_status = 'F')
            AND    gps.adjustment_period_flag   = 'N'
            AND    asp.set_of_books_id          > 0
            AND    ROWNUM = 1;

        RETURN l_period_name;
    EXCEPTION
        WHEN no_data_found THEN
            RETURN NULL;
        WHEN OTHERS THEN
            RETURN NULL;
    END get_period_name;
-- -------------------------------------------------------------------------
-- Get the primary ledger (set_of_books_id) for the new instance.
-- -------------------------------------------------------------------------
    FUNCTION get_sob_id RETURN NUMBER IS
        l_sob_id NUMBER;
    BEGIN
        SELECT MIN(set_of_books_id)
        INTO   l_sob_id
        FROM   AR_SYSTEM_PARAMETERS_ALL
        WHERE  set_of_books_id > 0;

        RETURN l_sob_id;
    EXCEPTION
        WHEN OTHERS THEN
            RETURN NULL;
    END get_sob_id;
-- -------------------------------------------------------------------------
-- Derive the GL journal category from the MTL transaction type ID.
-- Uses the pre-populated g_category_map collection.
-- Returns 'Inventory Accounting' as the default for unmapped types.
-- -------------------------------------------------------------------------
    FUNCTION get_je_category (
        p_txn_type_id IN NUMBER
    ) RETURN VARCHAR2 IS
    BEGIN
        IF g_category_map.EXISTS(p_txn_type_id) THEN
            RETURN g_category_map(p_txn_type_id);
        ELSE
            RETURN 'Inventory Accounting';
        END IF;
    END get_je_category;
-- -------------------------------------------------------------------------
-- Derive a source document reference string for GL journal descriptions.
-- Priority: PO number > SO number > WIP job > 'INV ADJ'
-- All joins are to the legacy instance via DB link.
-- -------------------------------------------------------------------------
    FUNCTION get_source_doc_ref (
        p_txn_type_id      IN NUMBER,
        p_source_header_id IN NUMBER,
        p_txn_source_type  IN VARCHAR2 -- MTL_MATERIAL_TRANSACTIONS.transaction_source_type_id
    ) RETURN VARCHAR2 IS
        l_ref VARCHAR2(100) := NULL;
    BEGIN -- PO Receipt types: look up PO number
        IF p_txn_type_id IN ( 1, 17, 27 ) THEN
            BEGIN
                SELECT
                    'PO#' || ph.segment1
                INTO l_ref
                FROM
                    apps.po_headers_all@legacy_instance ph
                WHERE
                        ph.po_header_id = p_source_header_id
                    AND ROWNUM = 1;

            EXCEPTION
                WHEN OTHERS THEN
                    l_ref := 'PO#UNKNOWN';
            END;
-- SO Issue types: look up Sales Order number
        ELSIF p_txn_type_id IN ( 33, 34 ) THEN
            BEGIN
                SELECT
                    'SO#' || oh.order_number
                INTO l_ref
                FROM
                    apps.oe_order_headers_all@legacy_instance oh
                WHERE
                        oh.header_id = p_source_header_id
                    AND ROWNUM = 1;

            EXCEPTION
                WHEN OTHERS THEN
                    l_ref := 'SO#UNKNOWN';
            END;
-- WIP types: look up job number
        ELSIF p_txn_type_id IN ( 35, 44 ) THEN
            BEGIN
                SELECT
                    'JOB#' || we.wip_entity_name
                INTO l_ref
                FROM
                    apps.wip_entities@legacy_instance we
                WHERE
                        we.wip_entity_id = p_source_header_id
                    AND ROWNUM = 1;

            EXCEPTION
                WHEN OTHERS THEN
                    l_ref := 'JOB#UNKNOWN';
            END;
-- Inter-org transfers
        ELSIF p_txn_type_id IN ( 2, 3, 21, 22 ) THEN
            l_ref := 'INTER-ORG';
-- Adjustments, standard cost update, miscellaneous
        ELSE
            CASE p_txn_type_id
                WHEN 4 THEN
                    l_ref := 'INV ADJ';
                WHEN 5 THEN
                    l_ref := 'MISC TXN';
                WHEN 24 THEN
                    l_ref := 'STD COST UPDATE';
                ELSE
                    l_ref := 'INV TXN';
            END CASE;
        END IF;

        RETURN nvl(l_ref, 'INV TXN');
    EXCEPTION
        WHEN OTHERS THEN
            RETURN 'INV TXN';
    END get_source_doc_ref;
-- -------------------------------------------------------------------------
-- Validate a single MTL accounting line before loading to GL_INTERFACE.
--
    -- Applies business rules BR-01 through BR-09 (see IDD Section 5).
--
    -- Parameters:
--   p_txn_type_id      : MTL_MATERIAL_TRANSACTIONS.transaction_type_id
--   p_mtl_txn_id       : MTL_MATERIAL_TRANSACTIONS.transaction_id
--   p_legacy_ccid      : MTL_TRANSACTION_ACCOUNTS.reference_account
--   p_base_txn_value   : MTL_TRANSACTION_ACCOUNTS.base_transaction_value
--   p_accounting_date  : MTL_MATERIAL_TRANSACTIONS.transaction_date
--   p_period_name      : Derived GL period (NULL = no open period found)
--   p_txn_balance      : SUM of all base_transaction_value lines for this txn
--                        (used for BR-03 journal balance check)
--   p_rejection_reason : OUT - populated on validation failure
--
    -- Returns TRUE if valid, FALSE if rejected.
-- -------------------------------------------------------------------------
    FUNCTION validate_transaction (
        p_txn_type_id      IN NUMBER,
        p_mtl_txn_id       IN NUMBER,
        p_legacy_ccid      IN NUMBER,
        p_base_txn_value   IN NUMBER,
        p_accounting_date  IN DATE,
        p_period_name      IN VARCHAR2,
        p_txn_balance      IN NUMBER,
        p_new_ccid         IN NUMBER,
        p_rejection_reason OUT VARCHAR2
    ) RETURN BOOLEAN IS
        l_already_processed NUMBER;
        l_ccid_enabled      VARCHAR2(1);
        l_ccid_summary      VARCHAR2(1);
    BEGIN
        p_rejection_reason := NULL;
-- BR-01: In-scope transaction type (enforced upstream by cursor WHERE clause)
-- Included here as a secondary safety check
        IF p_txn_type_id NOT IN ( 1, 2, 3, 4, 5,
                                  17, 21, 22, 24, 27,
                                  33, 34, 35, 44 ) THEN
            p_rejection_reason := 'BR-01: Transaction type '
                                  || p_txn_type_id
                                  || ' is not in the approved in-scope list.';
            RETURN FALSE;
        END IF;
-- BR-02: Non-zero accounting amount
        IF nvl(p_base_txn_value, 0) = 0 THEN
            p_rejection_reason := 'BR-02: base_transaction_value is zero. No GL entry required.';
            RETURN FALSE;
        END IF;
-- BR-03: Journal must balance (total of all accounting lines for this txn = 0)
-- A non-zero balance indicates a cost management issue in the legacy instance.
        IF abs(nvl(p_txn_balance, 1)) > 0.005 THEN
            p_rejection_reason := 'BR-03: Journal does not balance for transaction_id '
                                  || p_mtl_txn_id
                                  || '. SUM(base_transaction_value) = '
                                  || to_char(p_txn_balance, 'FM999,999,999.99')
                                  || '. Investigate in legacy Cost Management.';

            RETURN FALSE;
        END IF;
-- BR-04: No duplicate processing
        SELECT 
            COUNT(*) 
        INTO l_already_processed
        FROM   
            apps.xxcust_inv_gl_interface_log
        WHERE  
                legacy_mtl_txn_id    = p_mtl_txn_id
            AND    legacy_ccid          = p_legacy_ccid
            AND    interface_status     = c_status_processed
            AND    (   (p_base_txn_value > 0 AND entered_dr IS NOT NULL)
                    OR (p_base_txn_value < 0 AND entered_cr IS NOT NULL) );


        IF l_already_processed > 0 THEN
            p_rejection_reason := 'BR-04: Transaction ID '
                                  || p_mtl_txn_id
                                  || ' / CCID '
                                  || p_legacy_ccid
                                  || ' already processed. Duplicate skipped.';
            RETURN FALSE;
        END IF;
-- BR-05: COA mapping must exist with a non-null new_ccid
-- IF NVL(p_new_ccid, -1) = -1 THEN p_rejection_reason := 'BR-05: No active COA mapping for legacy CCID ' || p_legacy_ccid || '. Add to XXCUST_COA_MAPPING then rerun.';
-- RETURN FALSE;
-- END IF;
-- BR-06: GL period must be open or future-enterable in new instance
        IF p_period_name IS NULL THEN
            p_rejection_reason := 'BR-06: No open GL period found in new instance for '
                                  || 'accounting date '
                                  || to_char(p_accounting_date, 'DD-MON-YYYY')
                                  || '. Open the period in new GL and rerun.';

            RETURN FALSE;
        END IF;
-- BR-08: New CCID must be enabled and not a summary account
        BEGIN
            SELECT
                enabled_flag,
                summary_flag
            INTO
                l_ccid_enabled,
                l_ccid_summary
            FROM
                apps.gl_code_combinations
            WHERE
                code_combination_id = p_new_ccid;

            IF nvl(l_ccid_enabled, 'N') <> 'Y' THEN
                p_rejection_reason := 'BR-08: New CCID '
                                      || p_new_ccid
                                      || ' (mapped from legacy CCID '
                                      || p_legacy_ccid
                                      || ') is disabled in new GL_CODE_COMBINATIONS.';
                RETURN FALSE;
            END IF;

            IF nvl(l_ccid_summary, 'N') = 'Y' THEN
                p_rejection_reason := 'BR-08: New CCID '
                                      || p_new_ccid
                                      || ' is a summary account. Journal Import requires'
                                      || ' a detail (non-summary) code combination.';
                RETURN FALSE;
            END IF;

        EXCEPTION
            WHEN no_data_found THEN
                p_rejection_reason := 'BR-08: New CCID '
                                      || p_new_ccid
                                      || ' not found in new GL_CODE_COMBINATIONS.'
                                      || ' Update XXCUST_COA_MAPPING.new_ccid.';
                RETURN FALSE;
        END;
-- All checks passed
        RETURN TRUE;
    EXCEPTION
        WHEN OTHERS THEN
            p_rejection_reason := 'Unexpected validation error: ' || sqlerrm;
            RETURN FALSE;
    END validate_transaction;
-- -------------------------------------------------------------------------
-- Insert one accounting line into GL_INTERFACE and write a corresponding
-- row to XXCUST_INV_GL_INTERFACE_LOG.
--
    -- Centralises all GL_INTERFACE writes so the same path is used for every
-- transaction type and journal category.
-- -------------------------------------------------------------------------
    PROCEDURE load_gl_line (
    -- Run context
        p_run_id             IN VARCHAR2,
        p_group_id           IN NUMBER,
        p_sob_id             IN NUMBER,
    -- Journal attributes
        p_je_category        IN VARCHAR2,
        p_accounting_date    IN DATE,
        p_period_name        IN VARCHAR2,
        p_currency_code      IN VARCHAR2,
        p_conversion_rate    IN NUMBER,
    -- Amounts (one of entered_dr / entered_cr is populated; other is NULL)
        p_entered_dr         IN NUMBER,
        p_entered_cr         IN NUMBER,
    -- Account coding
        p_new_ccid           IN NUMBER,
        p_legacy_ccid        IN NUMBER,
        p_legacy_account_num IN VARCHAR2,
    -- Reference / description
        p_source_doc_ref     IN VARCHAR2,
    -- PO#, SO#, JOB#, INV ADJ etc.
        p_mtl_txn_id         IN NUMBER,
        p_txn_type_id        IN NUMBER,
        p_org_id             IN NUMBER,
        p_org_name           IN VARCHAR2,
        p_item_id            IN NUMBER,
        p_item_description   IN VARCHAR2,
    -- Log columns
        p_legacy_txn_type_id IN NUMBER
    ) IS
        l_accounted_dr NUMBER;
        l_accounted_cr NUMBER;
        l_conv_rate    NUMBER;
        l_description  VARCHAR2(240);
    BEGIN -- Derive functional currency amounts
        l_conv_rate := nvl(p_conversion_rate, 1);
        l_accounted_dr :=
            CASE
                WHEN p_entered_dr IS NOT NULL THEN
                    round(p_entered_dr * l_conv_rate, 2)
                ELSE NULL
            END;

        l_accounted_cr :=
            CASE
                WHEN p_entered_cr IS NOT NULL THEN
                    round(p_entered_cr * l_conv_rate, 2)
                ELSE NULL
            END;
-- Build journal line description
-- Format: {Category}: Org={org} | {source_ref} | {item_desc} | {date}
        l_description := substr(p_je_category
                                || ': Org='
                                || p_org_name
                                || ' | '
                                || p_source_doc_ref
                                || ' | '
                                || nvl(p_item_description, 'No Item')
                                || ' | TxnID='
                                || p_mtl_txn_id
                                || ' | '
                                || to_char(p_accounting_date, 'DD-MON-YYYY'),
                                1,
                                240);
-- ─────────────────────────────────────────────────────────────────────
-- INSERT into GL_INTERFACE
--
        -- Key columns explained:
--   status                  : NEW = unprocessed; Journal Import sets to P
--   set_of_books_id         : new instance ledger ID
--   actual_flag             : A = Actual journal
--   user_je_source_name     : XXCUST_INV_ACCT (registered source)
--   user_je_category_name   : Receiving / Inventory / COGS / WIP / Inv Accounting
--   group_id                : unique per run; used as Journal Import parameter
--   reference1              : source document (PO#, SO#, JOB#) for traceability
--   reference2              : legacy transaction_id (uniqueness + audit)
--   reference4              : full journal line description
--   reference10             : run_id ties back to XXCUST_INV_GL_INTERFACE_LOG
-- ─────────────────────────────────────────────────────────────────────
        INSERT INTO apps.gl_interface (
            status,
            set_of_books_id,
            accounting_date,
            currency_code,
            date_created,
            created_by,
            actual_flag,
            user_je_source_name,
            user_je_category_name,
            period_name,
            entered_dr,
            entered_cr,
            accounted_dr,
            accounted_cr,
            code_combination_id,
            reference1,
        -- source document reference
            reference2,
        -- legacy MTL transaction_id
            reference4,
        -- journal line description
            reference10,
        -- run_id (ties to log table)
            group_id
        ) VALUES ( 'NEW',
                   p_sob_id,
                   p_accounting_date,
                   p_currency_code,
                   sysdate,
                   c_created_by,
                   c_actual_flag,
                   c_gl_source,
                   p_je_category,
                   p_period_name,
                   p_entered_dr,
                   p_entered_cr,
                   l_accounted_dr,
                   l_accounted_cr,
                   p_new_ccid,
                   p_source_doc_ref,
                   to_char(p_mtl_txn_id),
                   l_description,
                   p_run_id,
                   p_group_id );
-- ─────────────────────────────────────────────────────────────────────
-- Log the successfully loaded line
-- ─────────────────────────────────────────────────────────────────────
        INSERT INTO apps.xxcust_inv_gl_interface_log (
            run_id,
            journal_category,
            legacy_mtl_txn_id,
            legacy_txn_type_id,
            legacy_org_id,
            legacy_org_name,
            legacy_item_id,
            legacy_item_description,
            legacy_ccid,
            legacy_account_num,
            new_ccid,
            accounting_date,
            period_name,
            currency_code,
            entered_dr,
            entered_cr,
            accounted_dr,
            accounted_cr,
            source_doc_reference,
            gl_interface_group_id,
            interface_status
        ) VALUES ( p_run_id,
                   p_je_category,
                   p_mtl_txn_id,
                   p_legacy_txn_type_id,
                   p_org_id,
                   p_org_name,
                   p_item_id,
                   p_item_description,
                   p_legacy_ccid,
                   p_legacy_account_num,
                   p_new_ccid,
                   p_accounting_date,
                   p_period_name,
                   p_currency_code,
                   p_entered_dr,
                   p_entered_cr,
                   l_accounted_dr,
                   l_accounted_cr,
                   p_source_doc_ref,
                   p_group_id,
                   c_status_processed );

    END load_gl_line;
-- =========================================================================
-- 3B: MAIN INTERFACE PROCEDURE -- run_interface
-- =========================================================================
    PROCEDURE run_interface (
        p_errbuf          OUT VARCHAR2,
        p_retcode         OUT NUMBER,
        p_group_id        OUT NUMBER,
        p_organization_id IN NUMBER DEFAULT NULL,
        p_txn_date_from   IN VARCHAR2 DEFAULT NULL,
        p_txn_date_to     IN VARCHAR2 DEFAULT NULL,
        p_txn_type_ids    IN VARCHAR2 DEFAULT NULL,
        p_debug_mode      IN VARCHAR2 DEFAULT 'N'
    ) IS -- ─────────────────────────────────────────────────────────────────────
-- MAIN EXTRACTION CURSOR
--
        -- Joins MTL_MATERIAL_TRANSACTIONS to MTL_TRANSACTION_ACCOUNTS
-- in the legacy instance via DB link.
--
        -- For each in-scope material transaction:
--   - Selects one row per accounting line (one per MTL_TRANSACTION_ACCOUNTS row)
--   - Derives entered_dr / entered_cr from the sign of base_transaction_value
--   - Computes the transaction balance (SUM across all lines for this txn)
--     so the balance check (BR-03) can be applied per line
--   - Joins to item master, organisation, and source document tables
--     for journal description and reference population
--
        -- BUSINESS RULE: base_transaction_value <> 0 (zero lines excluded)
-- BUSINESS RULE: transaction_type_id in the approved in-scope list
--
        -- NOTE: The WHERE clause uses a fixed IN list for all in-scope types.
--       If p_txn_type_ids is supplied, the cursor is rewritten at runtime
--       via dynamic SQL (see l_dynamic_cursor handling below).
--       For the static cursor we use the full in-scope list.
-- ─────────────────────────────────────────────────────────────────────
        CURSOR c_inv_accounting IS
        SELECT -- Transaction header
            mmt.transaction_id                                         mtl_txn_id,
            mmt.transaction_type_id                                    txn_type_id,
            mmt.transaction_date                                       accounting_date,
            mmt.organization_id                                        org_id,
            mmt.inventory_item_id                                      item_id,
            NVL(mmt.currency_code, 'INR')                                          currency_code,
            nvl(mmt.currency_conversion_rate, 1)                       conversion_rate,
            mmt.transaction_source_id                                  source_header_id,
            mmt.transaction_source_type_id                             txn_source_type_id,
    -- Accounting line (one row per GL distribution)
            mta.reference_account                                      legacy_ccid,
            mta.base_transaction_value                                 base_txn_value,
    -- Debit: positive base_transaction_value
            CASE
                WHEN mta.base_transaction_value > 0 THEN
                    mta.base_transaction_value
                ELSE
                    NULL
            END                                                        entered_dr,
    -- Credit: negative base_transaction_value stored as absolute value
            CASE
                WHEN mta.base_transaction_value < 0 THEN
                    - mta.base_transaction_value
                ELSE
                    NULL
            END                                                        entered_cr,
    -- Transaction balance across ALL accounting lines for this txn_id.
    -- Used for BR-03 journal balance check.
    -- A balanced transaction has SUM = 0.
            (
                SELECT
                    SUM(mta2.base_transaction_value)
                FROM
                    apps.mtl_transaction_accounts@legacy_instance mta2
                WHERE
                    mta2.transaction_id = mmt.transaction_id
            )                                                          AS txn_balance,
    -- Item description
            nvl(msi.description, 'Item ID: ' || mmt.inventory_item_id) item_description,
    -- Legacy concatenated account string (for logging and audit)
            gcc.segment1
            || '.'
            || gcc.segment2
            || '.'
            || gcc.segment3
            || '.'
            || gcc.segment4                                            legacy_account_num,
    -- Organisation name (for journal description)
            hou.name                                                   org_name
        FROM
                 apps.mtl_material_transactions@legacy_instance mmt
            JOIN apps.mtl_transaction_accounts@legacy_instance mta ON mta.transaction_id = mmt.transaction_id
            LEFT JOIN apps.mtl_system_items_b@legacy_instance       msi ON msi.inventory_item_id = mmt.inventory_item_id
                                                                     AND msi.organization_id = mmt.organization_id
            LEFT JOIN apps.gl_code_combinations@legacy_instance     gcc ON gcc.code_combination_id = mta.reference_account
            LEFT JOIN apps.hr_organization_units@legacy_instance    hou ON hou.organization_id = mmt.organization_id
        WHERE -- ── Core filter: in-scope transaction types only ──────────────
            mmt.transaction_type_id IN ( 1, 2, 3, 4, 5,
                                         17, 21, 22, 24, 27,
                                         33, 34, 35, 44 ) -- ── Exclude zero-value accounting lines (BR-02) ──────────────
            AND mta.base_transaction_value <> 0 -- ── Optional: restrict to a specific organisation ─────────────
            AND ( p_organization_id IS NULL
                  OR mmt.organization_id = p_organization_id ) -- ── Optional: date range filter ──────────────────────────────
            AND ( p_txn_date_from IS NULL
                  OR mmt.transaction_date >= TO_DATE(p_txn_date_from, 'DD-MON-YYYY') )
            AND ( p_txn_date_to IS NULL
                  OR mmt.transaction_date <= TO_DATE(p_txn_date_to, 'DD-MON-YYYY') + 1 ) -- ── Optional: restrict to specific transaction type(s) ────────
    -- When p_txn_type_ids is supplied as a CSV (e.g. '1,17,33'),
    -- we additionally filter using INSTR to match against the list.
    -- This is an approximate filter; the exact type check is enforced
    -- by the hard-coded IN list above.  Operators can pass e.g.
    -- p_txn_type_ids => '33' to process only SO Issues in a run.
            AND ( p_txn_type_ids IS NULL
                  OR instr(','
                           || p_txn_type_ids
                           || ',',
                           ','
                           || to_char(mmt.transaction_type_id)
                           || ',') > 0 )
        ORDER BY
            mmt.transaction_date,
            mmt.transaction_id,
            mta.reference_account;
-- ─────────────────────────────────────────────────────────────────────
-- Local variables
-- ─────────────────────────────────────────────────────────────────────
        l_run_id            VARCHAR2(50);
        l_sob_id            NUMBER;
        l_period_name       VARCHAR2(15);
        l_new_ccid          NUMBER;
        l_je_category       VARCHAR2(50);
        l_source_doc_ref    VARCHAR2(100);
        l_rejection_reason  VARCHAR2(2000);
        l_is_valid          BOOLEAN;
-- Counters
        l_cnt_processed     NUMBER := 0;
        l_cnt_rejected      NUMBER := 0;
        l_cnt_errored       NUMBER := 0;
        l_cnt_skipped       NUMBER := 0;
-- Track current transaction_id so we log rejection once per transaction
-- rather than once per accounting line
        l_last_rejected_txn NUMBER := -1;
        l_accounting_date   DATE;
    BEGIN
        p_retcode := 0;
-- ─────────────────────────────────────────────────────────────────────
-- Initialise run context
-- ─────────────────────────────────────────────────────────────────────
        l_run_id := c_run_prefix || to_char(sysdate, 'YYYYMMDDHH24MISS');
        l_sob_id := get_sob_id();
-- Allocate a unique group_id for this run from the GL sequence.
-- This group_id is passed to Journal Import as the batch identifier.
        SELECT
            gl_journal_import_s.NEXTVAL
        INTO p_group_id
        FROM
            dual;

        log_msg('=================================================================');
        log_msg('IF-03: INV to GL Interface -- Run ID : ' || l_run_id);
        log_msg('Group ID (Journal Import) : ' || p_group_id);
        log_msg('Ledger (SOB ID)           : ' || l_sob_id);
        log_msg('Organisation ID           : '
                || nvl(
            to_char(p_organization_id),
            'ALL'
        ));
        log_msg('Txn Date From             : ' || nvl(p_txn_date_from, 'NONE'));
        log_msg('Txn Date To               : ' || nvl(p_txn_date_to, 'NONE'));
        log_msg('Txn Type IDs              : ' || nvl(p_txn_type_ids, 'ALL IN-SCOPE'));
        log_msg('=================================================================');
-- ─────────────────────────────────────────────────────────────────────
-- MAIN PROCESSING LOOP
-- One iteration per accounting line (MTL_TRANSACTION_ACCOUNTS row).
-- ─────────────────────────────────────────────────────────────────────
        FOR r IN c_inv_accounting LOOP
            BEGIN -- ── STEP 1: Derive GL journal category from transaction type ──
                l_je_category := get_je_category(r.txn_type_id);
-- ── STEP 2: Derive GL period name — override to open period if original has none
                l_period_name := get_period_name(r.accounting_date);
                IF l_period_name IS NULL THEN
                    l_accounting_date := TRUNC(SYSDATE, 'MM');
                    l_period_name     := get_period_name(l_accounting_date);
                    log_msg('Accounting date overridden from '
                            || TO_CHAR(r.accounting_date, 'DD-MON-YYYY')
                            || ' to '
                            || TO_CHAR(l_accounting_date, 'DD-MON-YYYY')
                            || ' — original period not open in new GL');
                ELSE
                    l_accounting_date := r.accounting_date;
                END IF;

-- ── STEP 3: Lookup new COA CCID ───────────────────────────────
                l_new_ccid := derive_new_ccid(
                    p_legacy_ccid        => r.legacy_ccid,
                    p_inventory_org_id   => r.org_id,
                    p_inventory_item_id  => r.item_id,
                    p_rcv_transaction_id => r.source_header_id
                );
-- ── STEP 4: Validate this accounting line ─────────────────────
--
                -- The validate_transaction function applies BR-01 through BR-08.
-- If validation fails for one line of a transaction, the entire
-- transaction is rejected (we track l_last_rejected_txn to avoid
-- logging the same rejection message multiple times for multi-line
-- transactions).
                l_is_valid := validate_transaction(
                    p_txn_type_id      => r.txn_type_id,
                    p_mtl_txn_id       => r.mtl_txn_id,
                    p_legacy_ccid      => r.legacy_ccid,
                    p_base_txn_value   => r.base_txn_value,
                    p_accounting_date  => l_accounting_date,
                    p_period_name      => l_period_name,
                    p_txn_balance      => r.txn_balance,
                    p_new_ccid         => l_new_ccid,
                    p_rejection_reason => l_rejection_reason
                );

                IF NOT l_is_valid THEN -- Log rejection only once per transaction_id
                    IF r.mtl_txn_id <> l_last_rejected_txn THEN
                        INSERT INTO apps.xxcust_inv_gl_interface_log (
                            run_id,
                            journal_category,
                            legacy_mtl_txn_id,
                            legacy_txn_type_id,
                            legacy_org_id,
                            legacy_org_name,
                            legacy_item_id,
                            legacy_item_description,
                            legacy_ccid,
                            legacy_account_num,
                            accounting_date,
                            currency_code,
                            gl_interface_group_id,
                            interface_status,
                            rejection_reason
                        ) VALUES ( l_run_id,
                                   l_je_category,
                                   r.mtl_txn_id,
                                   r.txn_type_id,
                                   r.org_id,
                                   r.org_name,
                                   r.item_id,
                                   r.item_description,
                                   r.legacy_ccid,
                                   r.legacy_account_num,
                                   r.accounting_date,
                                   r.currency_code,
                                   p_group_id,
                                   c_status_rejected,
                                   l_rejection_reason );

                        l_last_rejected_txn := r.mtl_txn_id;
                        l_cnt_rejected := l_cnt_rejected + 1;
                        log_msg('REJECTED: TxnID='
                                || r.mtl_txn_id
                                || ' Type='
                                || r.txn_type_id
                                || ' Org='
                                || r.org_name
                                || ' | '
                                || l_rejection_reason);

                    ELSE -- Additional lines of the same already-rejected transaction
                        l_cnt_skipped := l_cnt_skipped + 1;
                    END IF;

                    CONTINUE;
                END IF;
-- ── STEP 5: Derive source document reference ──────────────────
                l_source_doc_ref := get_source_doc_ref(
                    p_txn_type_id      => r.txn_type_id,
                    p_source_header_id => r.source_header_id,
                    p_txn_source_type  => to_char(r.txn_source_type_id)
                );
-- ── STEP 6: Load to GL_INTERFACE and write log row ────────────
                load_gl_line(
                    p_run_id             => l_run_id,
                    p_group_id           => p_group_id,
                    p_sob_id             => l_sob_id,
                    p_je_category        => l_je_category,
                    p_accounting_date    => l_accounting_date,
                    p_period_name        => l_period_name,
                    p_currency_code      => r.currency_code,
                    p_conversion_rate    => r.conversion_rate,
                    p_entered_dr         => r.entered_dr,
                    p_entered_cr         => r.entered_cr,
                    p_new_ccid           => l_new_ccid,
                    p_legacy_ccid        => r.legacy_ccid,
                    p_legacy_account_num => r.legacy_account_num,
                    p_source_doc_ref     => l_source_doc_ref,
                    p_mtl_txn_id         => r.mtl_txn_id,
                    p_txn_type_id        => r.txn_type_id,
                    p_org_id             => r.org_id,
                    p_org_name           => r.org_name,
                    p_item_id            => r.item_id,
                    p_item_description   => r.item_description,
                    p_legacy_txn_type_id => r.txn_type_id
                );

                l_cnt_processed := l_cnt_processed + 1;
                IF p_debug_mode = 'Y' THEN
                    log_msg('PROCESSED: TxnID='
                            || r.mtl_txn_id
                            || ' Type='
                            || r.txn_type_id
                            || ' Cat='
                            || l_je_category
                            || ' CCID: '
                            || r.legacy_ccid
                            || '->'
                            || l_new_ccid
                            || ' DR='
                            || nvl(
                        to_char(r.entered_dr),
                        'null'
                    )
                            || ' CR='
                            || nvl(
                        to_char(r.entered_cr),
                        'null'
                    ));
                END IF;

            EXCEPTION -- ── Per-record exception handler ──────────────────────────────
-- Catches unexpected errors on individual lines.
-- Logs the error and continues to the next record.
                WHEN OTHERS THEN
                    DECLARE
                        l_err_msg VARCHAR2(2000) := substr(sqlerrm, 1, 2000);
                    BEGIN
                        INSERT INTO apps.xxcust_inv_gl_interface_log (
                            run_id,
                            journal_category,
                            legacy_mtl_txn_id,
                            legacy_txn_type_id,
                            legacy_org_id,
                            legacy_org_name,
                            legacy_item_id,
                            legacy_ccid,
                            accounting_date,
                            gl_interface_group_id,
                            interface_status,
                            rejection_reason
                        ) VALUES ( l_run_id,
                                   l_je_category,
                                   r.mtl_txn_id,
                                   r.txn_type_id,
                                   r.org_id,
                                   r.org_name,
                                   r.item_id,
                                   r.legacy_ccid,
                                   l_accounting_date,
                                   p_group_id,
                                   c_status_error,
                                   'Unexpected error on TxnID='
                                   || r.mtl_txn_id
                                   || ' CCID='
                                   || r.legacy_ccid
                                   || ': '
                                   || l_err_msg );

                    EXCEPTION
                        WHEN OTHERS THEN
                            NULL;
-- Prevent log insert failure from crashing the run
                    END;

                    l_cnt_errored := l_cnt_errored + 1;
                    log_msg('ERROR: TxnID='
                            || r.mtl_txn_id
                            || ' CCID='
                            || r.legacy_ccid
                            || ' | '
                            || sqlerrm);

            END;
        END LOOP;
-- ─────────────────────────────────────────────────────────────────────
-- Commit all GL_INTERFACE and log inserts
-- ─────────────────────────────────────────────────────────────────────
        COMMIT;
-- ─────────────────────────────────────────────────────────────────────
-- Run summary
-- ─────────────────────────────────────────────────────────────────────
        log_msg('=================================================================');
        log_msg('IF-03 Complete -- Run ID  : ' || l_run_id);
        log_msg('  GL lines processed     : ' || l_cnt_processed);
        log_msg('  Transactions rejected  : ' || l_cnt_rejected);
        log_msg('  Lines skipped (rej txn): ' || l_cnt_skipped);
        log_msg('  Errors                 : ' || l_cnt_errored);
        log_msg('-----------------------------------------------------------------');
        log_msg('Next step: Run Journal Import in new GL instance:');
        log_msg('  Source   : ' || c_gl_source);
        log_msg('  Group ID : ' || p_group_id);
        log_msg('  Nav: General Ledger > Journals > Import > Run');
        log_msg('=================================================================');
-- Set return code: 0 = success, 1 = warning (rejections/errors), 2 = error
        IF l_cnt_errored > 0 THEN
            p_retcode := 1;
            p_errbuf := 'IF-03 completed with '
                        || l_cnt_rejected
                        || ' rejections and '
                        || l_cnt_errored
                        || ' errors. Review XXCUST_INV_GL_INTERFACE_LOG run_id='
                        || l_run_id;

        ELSIF l_cnt_rejected > 0 THEN
            p_retcode := 1;
            p_errbuf := 'IF-03 completed with '
                        || l_cnt_rejected
                        || ' rejections. Review XXCUST_INV_GL_INTERFACE_LOG run_id='
                        || l_run_id;
        ELSE
            p_errbuf := 'IF-03 completed successfully. Group ID: ' || p_group_id;
        END IF;

    EXCEPTION -- ── Fatal exception handler ───────────────────────────────────────────
-- Rolls back uncommitted work and returns retcode 2.
        WHEN OTHERS THEN
            ROLLBACK;
            p_retcode := 2;
            p_errbuf := 'IF-03 FATAL ERROR: ' || sqlerrm;
            log_msg('FATAL ERROR (IF-03): ' || sqlerrm);
            log_msg(dbms_utility.format_error_backtrace());
    END run_interface;
-- =========================================================================
-- 3C: PURGE LOG
-- =========================================================================
    PROCEDURE purge_log (
        p_days_to_keep IN NUMBER DEFAULT 90
    ) IS
        l_count NUMBER;
    BEGIN
        DELETE FROM apps.xxcust_inv_gl_interface_log
        WHERE
                creation_date < sysdate - p_days_to_keep
            AND interface_status = c_status_processed;

        l_count := SQL%rowcount;
        COMMIT;
        log_msg('IF-03 purge complete: '
                || l_count
                || ' processed log records deleted.');
    END purge_log;
-- =========================================================================
-- PACKAGE INITIALISATION BLOCK
--
    -- Populates the journal category map (g_category_map) keyed by
-- MTL transaction_type_id. Called once when the package is first
-- loaded into the session.
-- =========================================================================
BEGIN -- PO Receipt stages
    g_category_map(1) := 'Receiving';
-- PO Receipt into Inspection
    g_category_map(27) := 'Receiving';
-- Return PO Receipt into Inspection
    g_category_map(17) := 'Receiving';
-- PO Deliver to Subinventory / RMA Receipt
-- Inventory transfers
    g_category_map(2) := 'Inventory';
-- Subinventory Transfer
    g_category_map(3) := 'Inventory';
-- Direct Inter-Org Transfer
    g_category_map(21) := 'Inventory';
-- Intransit Shipment
    g_category_map(22) := 'Inventory';
-- Intransit Receipt
-- Sales Order Issues
    g_category_map(33) := 'Cost of Goods Sold';
-- Sales Order Issue (COGS)
    g_category_map(34) := 'Inventory Accounting';
-- Account Alias Issue
-- Adjustments and miscellaneous
    g_category_map(4) := 'Inventory Accounting';
-- Cycle Count / Physical Inv / Misc Adj
    g_category_map(5) := 'Inventory Accounting';
-- Miscellaneous Issue / Receipt
    g_category_map(24) := 'Inventory Accounting';
-- Standard Cost Update
-- WIP transactions
    g_category_map(35) := 'WIP';
-- WIP Component Issue
    g_category_map(44) := 'WIP';
-- WIP Assembly Completion
END xxcust_inv_gl_interface_pkg;
/
/* ============================================================================
 SECTION 4: RECONCILIATION QUERIES
 ============================================================================ */
-- ---------------------------------------------------------------------------
-- Query 4A: MTL Accounting Lines vs Interface Log
--
-- Purpose  : Confirm all qualifying MTL_TRANSACTION_ACCOUNTS records for
--            the date range were processed or rejected.
-- When     : Run BEFORE Journal Import to verify the interface loaded correctly.
-- Expected : reconciliation_status = 'OK' for all rows.
-- ---------------------------------------------------------------------------
SELECT
    mmt.transaction_id,
    mmt.transaction_type_id,
    mmt.transaction_date,
    mta.reference_account     legacy_ccid,
    gcc.concatenated_segments legacy_account,
    mta.base_transaction_value,
    hou.name                  org_name,
    log.run_id,
    log.journal_category,
    log.period_name,
    log.new_ccid,
    log.interface_status,
    log.rejection_reason,
    CASE
        WHEN log.legacy_mtl_txn_id IS NULL THEN
            '** NOT INTERFACED — missing from log'
        WHEN log.interface_status = 'PROCESSED' THEN
            'OK — loaded to GL_INTERFACE'
        WHEN log.interface_status = 'REJECTED'  THEN
            'REJECTED: ' || log.rejection_reason
        WHEN log.interface_status = 'ERROR'     THEN
            'ERROR: ' || log.rejection_reason
        ELSE
            log.interface_status
    END                       reconciliation_status
FROM
         apps.mtl_material_transactions@legacy_instance mmt
    JOIN apps.mtl_transaction_accounts@legacy_instance mta ON mta.transaction_id = mmt.transaction_id
    LEFT JOIN apps.gl_code_combinations@legacy_instance     gcc ON gcc.code_combination_id = mta.reference_account
    LEFT JOIN apps.hr_organization_units@legacy_instance    hou ON hou.organization_id = mmt.organization_id
    LEFT JOIN xxcust_inv_gl_interface_log                   log ON log.legacy_mtl_txn_id = mmt.transaction_id
                                                 AND log.legacy_ccid = mta.reference_account
WHERE
    mmt.transaction_type_id IN ( 1, 2, 3, 4, 5,
                                 17, 21, 22, 24, 27,
                                 33, 34, 35, 44 )
    AND mta.base_transaction_value <> 0
    AND mmt.transaction_date BETWEEN :p_date_from AND :p_date_to
ORDER BY
    reconciliation_status,
    mmt.transaction_date,
    mmt.transaction_id,
    mta.reference_account;
-- ---------------------------------------------------------------------------
-- Query 4B: GL_INTERFACE vs GL_JE_LINES
--
-- Purpose  : Confirm Journal Import successfully created GL journal lines
--            for every row loaded to GL_INTERFACE.
-- When     : Run AFTER Journal Import program completes.
-- Expected : reconciliation_status = 'OK' for all rows.
-- Parameter: :p_group_id — from the interface run output log.
-- ---------------------------------------------------------------------------
SELECT
    gli.group_id,
    gli.user_je_category_name journal_category,
    gli.accounting_date,
    gli.period_name,
    gli.code_combination_id   new_ccid,
    gli.entered_dr,
    gli.entered_cr,
    gli.reference1            source_doc,
    gli.reference2            mtl_txn_id,
    gli.interface_status      gl_interface_status,
    jl.je_line_num            gl_je_line_num,
    jh.name                   gl_journal_name,
    jb.name                   gl_batch_name,
    jb.status                 batch_status,
    CASE
        WHEN jl.je_line_num IS NOT NULL THEN
            'OK — GL Journal created'
        WHEN gli.interface_status = 'E' THEN
            'GL IMPORT ERROR — check Journal Import execution report'
        ELSE
            'NOT IMPORTED — rerun Journal Import with Group ID=' || gli.group_id
    END                       reconciliation_status
FROM
    gl_interface  gli
    LEFT JOIN gl_je_lines   jl ON jl.code_combination_id = gli.code_combination_id
                                AND nvl(jl.entered_dr, 0) = nvl(gli.entered_dr, 0)
                                AND nvl(jl.entered_cr, 0) = nvl(gli.entered_cr, 0)
                                AND jl.reference_1 = gli.reference1
    LEFT JOIN gl_je_headers jh ON jh.je_header_id = jl.je_header_id
    LEFT JOIN gl_je_batches jb ON jb.je_batch_id = jh.je_batch_id
WHERE
        gli.user_je_source_name = 'XXCUST_INV_ACCT'
    AND gli.group_id = :p_group_id
ORDER BY
    reconciliation_status,
    gli.accounting_date,
    gli.user_je_category_name,
    gli.reference2;
-- ---------------------------------------------------------------------------
-- Query 4C: Journal Balance Check
--
-- Purpose  : Confirm total debits equal total credits for every journal
--            category within the group_id. Any non-zero variance must be
--            investigated before posting to the GL.
-- When     : Run AFTER loading GL_INTERFACE, BEFORE or AFTER Journal Import.
-- Expected : balance_status = 'BALANCED' for all rows.
--            variance = 0.00 for all rows.
-- ---------------------------------------------------------------------------
SELECT
    gli.group_id,
    gli.period_name,
    gli.user_je_category_name                                 journal_category,
    COUNT(*)                                                  line_count,
    SUM(nvl(gli.entered_dr, 0))                               total_dr,
    SUM(nvl(gli.entered_cr, 0))                               total_cr,
    SUM(nvl(gli.entered_dr, 0)) - SUM(nvl(gli.entered_cr, 0)) variance,
    CASE
        WHEN abs(sum(nvl(gli.entered_dr, 0)) - sum(nvl(gli.entered_cr, 0))) < 0.01 THEN
            'BALANCED'
        ELSE
            'OUT OF BALANCE -- INVESTIGATE BEFORE POSTING'
    END                                                       balance_status
FROM
    gl_interface gli
WHERE
        gli.user_je_source_name = 'XXCUST_INV_ACCT'
    AND gli.group_id = :p_group_id
GROUP BY
    gli.group_id,
    gli.period_name,
    gli.user_je_category_name
ORDER BY
    balance_status DESC,
    gli.period_name,
    gli.user_je_category_name;
-- ---------------------------------------------------------------------------
-- Query 4D: Inventory Valuation Amount Reconciliation
--
-- Purpose  : Confirm the total inventory accounting value loaded to the new
--            GL matches the total from legacy MTL_TRANSACTION_ACCOUNTS for
--            the same date range and organisation scope.
--            Compares debit-side totals (entered_dr).
-- When     : Run after GL_INTERFACE is loaded (before or after Journal Import).
-- Expected : Both source and target totals should match.
-- ---------------------------------------------------------------------------
SELECT
    'LEGACY: MTL_TRANSACTION_ACCOUNTS (debit lines)' data_source,
    COUNT(DISTINCT mmt.transaction_id)               transaction_count,
    SUM(mta.base_transaction_value)                  total_dr_amount
FROM
         apps.mtl_material_transactions@legacy_instance mmt
    JOIN apps.mtl_transaction_accounts@legacy_instance mta ON mta.transaction_id = mmt.transaction_id
WHERE
    mmt.transaction_type_id IN ( 1, 2, 3, 4, 5,
                                 17, 21, 22, 24, 27,
                                 33, 34, 35, 44 )
    AND mta.base_transaction_value > 0 -- Debit side only
    AND mmt.transaction_date BETWEEN :p_date_from AND :p_date_to
    AND ( p_organization_id IS NULL
          OR mmt.organization_id = :p_org_id )
UNION ALL
SELECT
    'NEW: GL_INTERFACE (entered_dr — debit lines)' data_source,
    COUNT(*)                                       transaction_count,
    SUM(nvl(gli.entered_dr, 0))                    total_dr_amount
FROM
    gl_interface gli
WHERE
        gli.user_je_source_name = 'XXCUST_INV_ACCT'
    AND gli.accounting_date BETWEEN :p_date_from AND :p_date_to
    AND gli.entered_dr IS NOT NULL;
-- ---------------------------------------------------------------------------
-- Query 4E: Interface Log Summary by Status and Journal Category
--
-- Purpose  : High-level summary of interface results for a given run.
-- When     : After each interface run.
-- ---------------------------------------------------------------------------
SELECT
    log.run_id,
    log.journal_category,
    log.interface_status,
    COUNT(*)                              line_count,
    COUNT(DISTINCT log.legacy_mtl_txn_id) transaction_count,
    SUM(nvl(log.entered_dr, 0))           total_dr,
    SUM(nvl(log.entered_cr, 0))           total_cr,
    MIN(log.accounting_date)              earliest_date,
    MAX(log.accounting_date)              latest_date
FROM
    xxcust_inv_gl_interface_log log
WHERE
    log.run_id = :p_run_id
GROUP BY
    log.run_id,
    log.journal_category,
    log.interface_status
ORDER BY
    log.interface_status,
    log.journal_category;
-- ---------------------------------------------------------------------------
-- Query 4F: Unmapped CCIDs — Pre-run check
--
-- Purpose  : Before running the interface, identify any legacy CCIDs
--            referenced by in-scope MTL_TRANSACTION_ACCOUNTS records that
--            are NOT yet in XXCUST_COA_MAPPING.
--            Run this query first. All rows should be resolved before
--            executing the interface.
-- When     : Before first interface run, and after any new accounts are
--            created in the legacy instance.
-- Expected : 0 rows returned.
-- ---------------------------------------------------------------------------
SELECT DISTINCT
    mta.reference_account                    legacy_ccid,
    gcc.concatenated_segments                legacy_account_num,
    mmt.transaction_type_id                  txn_type_id,
    hou.name                                 org_name,
    COUNT(mta.transaction_id)
    OVER(PARTITION BY mta.reference_account) affected_line_count
FROM
         apps.mtl_material_transactions@legacy_instance mmt
    JOIN apps.mtl_transaction_accounts@legacy_instance mta ON mta.transaction_id = mmt.transaction_id
    LEFT JOIN apps.gl_code_combinations@legacy_instance     gcc ON gcc.code_combination_id = mta.reference_account
    LEFT JOIN apps.hr_organization_units@legacy_instance    hou ON hou.organization_id = mmt.organization_id
WHERE
    mmt.transaction_type_id IN ( 1, 2, 3, 4, 5,
                                 17, 21, 22, 24, 27,
                                 33, 34, 35, 44 )
    AND mta.base_transaction_value <> 0
    AND mmt.transaction_date BETWEEN :p_date_from AND :p_date_to
    AND NOT EXISTS (
        SELECT
            1
        FROM
            xxcust_coa_mapping
        WHERE
                legacy_ccid = mta.reference_account
            AND mapping_status = 'ACTIVE'
            AND new_ccid IS NOT NULL
    )
ORDER BY
    mta.reference_account;
/* ============================================================================
 SECTION 5: EXECUTION GUIDE
 ============================================================================
 
 ── ONE-TIME SETUP ──────────────────────────────────────────────────────────
 
 1. Execute DDL (Section 1) to create XXCUST_INV_GL_INTERFACE_LOG
 in the new instance schema.
 
 2. Create DB link on the new instance (if not already created):
 CREATE DATABASE LINK LEGACY_INSTANCE
 CONNECT TO <legacy_schema_user> IDENTIFIED BY <password>
 USING '<legacy_tns_alias>';
 
 3. Grant SELECT on all legacy source tables to the DB link user:
 GRANT SELECT ON MTL_MATERIAL_TRANSACTIONS      TO <db_link_user>;
 GRANT SELECT ON MTL_TRANSACTION_ACCOUNTS       TO <db_link_user>;
 GRANT SELECT ON MTL_SYSTEM_ITEMS_B             TO <db_link_user>;
 GRANT SELECT ON MTL_PARAMETERS                 TO <db_link_user>;
 GRANT SELECT ON GL_CODE_COMBINATIONS           TO <db_link_user>;
 GRANT SELECT ON GL_PERIODS                     TO <db_link_user>;
 GRANT SELECT ON HR_ORGANIZATION_UNITS          TO <db_link_user>;
 GRANT SELECT ON PO_HEADERS_ALL                 TO <db_link_user>;
 GRANT SELECT ON OE_ORDER_HEADERS_ALL           TO <db_link_user>;
 GRANT SELECT ON WIP_DISCRETE_JOBS              TO <db_link_user>;
 GRANT SELECT ON CST_COST_GROUPS                TO <db_link_user>;
 
 4. Register GL Journal Source in new GL instance:
 General Ledger > Setup > Journals > Sources
 Source Name : XXCUST_INV_ACCT
 Description : Legacy Inventory Accounting Interface
 
 5. Register GL Journal Categories in new GL instance:
 General Ledger > Setup > Journals > Categories
 Categories required:
 - Receiving
 - Inventory
 - Cost of Goods Sold
 - Inventory Accounting
 - WIP
 
 6. Populate XXCUST_COA_MAPPING for all inventory account CCIDs.
 Run Query 4F first to identify all CCIDs that need mapping.
 Account types required:
 - Inventory Valuation (all sub-inventories and orgs in scope)
 - Receiving Inspection
 - AP Accrual (GRIR)
 - COGS
 - Deferred COGS (if revenue deferral is in use)
 - Intransit Inventory
 - WIP Valuation
 - Inventory Adjustment / Variance accounts
 - Standard Cost Revaluation accounts
 
 7. Compile the package in the new instance:
 @INV_to_GL_Interface.sql
 
 ── NIGHTLY RUN SEQUENCE ────────────────────────────────────────────────────
 
 Step 1: (Optional) Pre-run unmapped CCID check
 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 -- Run Query 4F to confirm no unmapped CCIDs exist.
 -- Resolve any rows returned before proceeding.
 
 Step 2: Run the interface
 ~~~~~~~~~~~~~~~~~~~~~~~~~~
 DECLARE
 l_errbuf    VARCHAR2(2000);
 l_retcode   NUMBER;
 l_group_id  NUMBER;
 BEGIN
 XXCUST_INV_GL_INTERFACE_PKG.run_interface(
 p_errbuf           => l_errbuf,
 p_retcode          => l_retcode,
 p_group_id         => l_group_id,     -- capture for Journal Import
 p_organization_id  => NULL,           -- NULL = all organisations
 p_txn_date_from    => TO_CHAR(TRUNC(SYSDATE-1),'DD-MON-YYYY'),
 p_txn_date_to      => TO_CHAR(TRUNC(SYSDATE-1),'DD-MON-YYYY'),
 p_txn_type_ids     => NULL,           -- NULL = all in-scope types
 p_debug_mode       => 'N'
 );
 DBMS_OUTPUT.PUT_LINE('Return Code : ' || l_retcode);
 DBMS_OUTPUT.PUT_LINE('Message     : ' || l_errbuf);
 DBMS_OUTPUT.PUT_LINE('Group ID    : ' || l_group_id);
 -- Note the Group ID -- required for Step 3
 END;
 /
 
 Step 3: Run Journal Import in new GL instance
 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 Navigation: General Ledger > Journals > Import > Run
 Parameters:
 Source               : XXCUST_INV_ACCT
 Group ID             : <value from Step 2 l_group_id output>
 Post Errors to Suspense  : No
 Create Summary Journals  : No (recommended -- use detail journals)
 
 Step 4: Reconcile
 ~~~~~~~~~~~~~~~~~~
 -- 4A: Verify all MTL lines were loaded (before Journal Import if possible)
 -- 4B: Verify GL journal lines created (after Journal Import)
 -- 4C: Confirm journals are balanced
 -- 4D: Confirm inventory valuation totals match
 -- 4E: Review run summary by journal category and status
 
 ── SELECTIVE RERUN (rejected transactions only) ────────────────────────────
 
 After fixing the root cause (open period, missing COA mapping, etc.),
 rerun for only the affected date range or specific transaction types:
 
 DECLARE
 l_errbuf    VARCHAR2(2000);
 l_retcode   NUMBER;
 l_group_id  NUMBER;
 BEGIN
 XXCUST_INV_GL_INTERFACE_PKG.run_interface(
 p_errbuf           => l_errbuf,
 p_retcode          => l_retcode,
 p_group_id         => l_group_id,
 p_organization_id  => NULL,
 p_txn_date_from    => '01-JAN-2025',
 p_txn_date_to      => '31-JAN-2025',
 p_txn_type_ids     => '33',       -- SO Issues only, for example
 p_debug_mode       => 'Y'         -- Y for detailed line-level logging
 );
 DBMS_OUTPUT.PUT_LINE('Group ID: ' || l_group_id);
 END;
 /
 
 ── MONTHLY PERIOD-END RUN ───────────────────────────────────────────────────
 
 Recommended sequence at month-end:
 
 1. Confirm inventory accounting period is CLOSED in legacy instance.
 2. Run Query 4F to confirm all CCIDs are mapped.
 3. Run interface for the full period:
 p_txn_date_from => '01-JAN-2025'
 p_txn_date_to   => '31-JAN-2025'
 4. Run Journal Import.
 5. Run reconciliation queries 4A-4E.
 6. Compare GL_INTERFACE totals with legacy Inventory Valuation Report
 (run in legacy instance for the same period and organisation).
 7. Obtain GL accountant sign-off before closing the GL period in new instance.
 
 ── PURGING OLD LOG RECORDS ──────────────────────────────────────────────────
 
 BEGIN
 XXCUST_INV_GL_INTERFACE_PKG.purge_log(p_days_to_keep => 90);
 END;
 /
 
 ============================================================================ */