--------------------------------------------------------
--  File created - Wednesday-May-06-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MAPPING_ORDER_TYPE
--------------------------------------------------------

  CREATE TABLE "APPS"."MAPPING_ORDER_TYPE" 
   (	"OLD_ORDER_TYPE_ID" NUMBER, 
	"OLD_ORDER_TYPE_NAME" VARCHAR2(240 BYTE), 
	"NEW_CUST_TRX_TYPE_NAME" VARCHAR2(240 BYTE), 
	"NEW_BATCH_SOURCE_NAME" VARCHAR2(240 BYTE), 
	"DESCRIPTION" VARCHAR2(240 BYTE), 
	"ENABLED_FLAG" VARCHAR2(1 BYTE) DEFAULT 'Y', 
	"CREATION_DATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
REM INSERTING into APPS.MAPPING_ORDER_TYPE
SET DEFINE OFF;
Insert into APPS.MAPPING_ORDER_TYPE (OLD_ORDER_TYPE_ID,OLD_ORDER_TYPE_NAME,NEW_CUST_TRX_TYPE_NAME,NEW_BATCH_SOURCE_NAME,DESCRIPTION,ENABLED_FLAG,CREATION_DATE) values (1026,null,'Credit Memo','BAMUL_OM_IMPORT',null,'Y',to_date('28-04-26','DD-MM-RR'));
Insert into APPS.MAPPING_ORDER_TYPE (OLD_ORDER_TYPE_ID,OLD_ORDER_TYPE_NAME,NEW_CUST_TRX_TYPE_NAME,NEW_BATCH_SOURCE_NAME,DESCRIPTION,ENABLED_FLAG,CREATION_DATE) values (1009,'BMD-ROUTE SALES','Bamul Route Sales','BAMUL_OM_IMPORT','Route Sales','Y',to_date('17-04-26','DD-MM-RR'));
Insert into APPS.MAPPING_ORDER_TYPE (OLD_ORDER_TYPE_ID,OLD_ORDER_TYPE_NAME,NEW_CUST_TRX_TYPE_NAME,NEW_BATCH_SOURCE_NAME,DESCRIPTION,ENABLED_FLAG,CREATION_DATE) values (1030,'BMD-P&I SALES - DCS SALES','Bamul P&I Sales','BAMUL_OM_IMPORT','P&I DCS Sales','Y',to_date('17-04-26','DD-MM-RR'));
--------------------------------------------------------
--  DDL for Index MAPPING_ORDER_TYPE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS"."MAPPING_ORDER_TYPE_PK" ON "APPS"."MAPPING_ORDER_TYPE" ("OLD_ORDER_TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  Constraints for Table MAPPING_ORDER_TYPE
--------------------------------------------------------

  ALTER TABLE "APPS"."MAPPING_ORDER_TYPE" MODIFY ("OLD_ORDER_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "APPS"."MAPPING_ORDER_TYPE" MODIFY ("NEW_CUST_TRX_TYPE_NAME" NOT NULL ENABLE);
  ALTER TABLE "APPS"."MAPPING_ORDER_TYPE" MODIFY ("NEW_BATCH_SOURCE_NAME" NOT NULL ENABLE);
  ALTER TABLE "APPS"."MAPPING_ORDER_TYPE" ADD CONSTRAINT "MAPPING_ORDER_TYPE_PK" PRIMARY KEY ("OLD_ORDER_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA"  ENABLE;
