--------------------------------------------------------
--  File created - Wednesday-May-06-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MAPPING_ITEM_KEYWORD_ACCOUNT
--------------------------------------------------------

  CREATE TABLE "APPS"."MAPPING_ITEM_KEYWORD_ACCOUNT" 
   (	"KEYWORD_ID" NUMBER(4,0), 
	"KEYWORD_PATTERN" VARCHAR2(200 BYTE), 
	"NEW_ACCOUNT_FLEX_VALUE" NUMBER(6,0), 
	"ACCOUNT_DESCRIPTION" VARCHAR2(100 BYTE), 
	"PRIORITY" NUMBER(2,0) DEFAULT 10
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
REM INSERTING into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT
SET DEFINE OFF;
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (1,'LDPE FILM%',513003,'Packing Materials',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (2,'%CORRUGATED BOX%',513003,'Packing Materials',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (3,'%PLY%BOX%',513003,'Packing Materials',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (4,'%STICKER%',513003,'Packing Materials',2);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (5,'%SHRINK%WRAP%',513003,'Packing Materials',2);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (6,'%PACKAGING%',513003,'Packing Materials',2);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (7,'%BERI CAPS%',513003,'Packing Materials',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (8,'%FLEXISPOUT%',513003,'Packing Materials',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (9,'%FLOW WRAP%',513003,'Packing Materials',2);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (10,'%GUNNY BAG%',513003,'Packing Materials',2);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (11,'%JUTE%BAG%',513003,'Packing Materials',2);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (12,'%WOODEN CRATE%',513003,'Packing Materials',2);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (13,'%STRAPPING%',513003,'Packing Materials',3);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (20,'%SUGAR%GRADE%',513002,'Raw Materials',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (21,'%GLYCEROL%',513002,'Raw Materials',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (22,'%GLYCERINE%',513002,'Raw Materials',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (23,'%REAGENT%',513002,'Raw Materials',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (24,'%SULPHURIC ACID%',513002,'Raw Materials',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (25,'%SODIUM%',513002,'Raw Materials',5);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (26,'%POTASSIUM%',513002,'Raw Materials',5);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (27,'%FURFURAL%',513002,'Raw Materials',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (28,'%AMYL ALCOHOL%',513002,'Raw Materials',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (29,'%CULTURE%',513002,'Raw Materials',5);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (30,'%BORAX%',513002,'Raw Materials',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (31,'%SILVER SULPHATE%',513002,'Raw Materials',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (32,'%AMYLE ALCOHOL%',513002,'Raw Materials',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (33,'%CONCENTRATE%',513002,'Raw Materials',8);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (34,'%DRY GRAPES%',513002,'Raw Materials',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (35,'%FURNACE OIL%',513002,'Raw Materials',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (40,'%VETDRUG%',512001,'Vet Drugs - P&I Trading',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (41,'ECOSPIRIN%',512001,'Vet Drug',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (42,'%OXYTETRACYCLIN%',512001,'Vet Drug',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (43,'%SULPHADEMI%',512001,'Vet Drug',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (44,'%MELOXICAM%',512001,'Vet Drug',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (45,'%CEFELACTUM%',512001,'Vet Drug',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (46,'%OXFEN%VET%',512001,'Vet Drug',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (47,'%FLUMAN%',512001,'Vet Drug',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (48,'%CIPROSAFE%',512001,'Vet Drug',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (49,'%ENTROVET%',512001,'Vet Drug',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (50,'%APTHOCARE%',512001,'Vet Drug',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (51,'%GENTIAN VOILET%',512001,'Vet Drug',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (52,'%BILKET%',512001,'Vet Drug',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (53,'%DEWORMING%',512001,'Vet Drug',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (54,'%DEHORNING%',512001,'Vet Drug',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (55,'%BILFENFORTE%',512001,'Vet Drug',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (56,'%BENZAN%',512001,'Vet Drug',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (57,'%CLOZENT%',512001,'Vet Drug',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (58,'%AMASTIC%',512001,'Vet Drug',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (59,'%KANTIRAZ%',512001,'Vet Drug',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (60,'%LOSAR H%',512001,'Vet Drug',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (61,'%BUDECORT%',512001,'Vet Drug',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (62,'%FORACORT%',512001,'Vet Drug',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (63,'%BLOATARID%',512001,'Vet Drug',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (64,'%MARIGOLD%CREAM%',512001,'Vet Drug',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (65,'%ATORVA%',512001,'Vet Drug',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (66,'%NICOSTAR%',512001,'Vet Drug',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (67,'%MASTILEP%',512001,'Vet Drug',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (68,'%STERIPAD%',512001,'Vet Drug/Medical',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (69,'%DISPOVAN%',512001,'Vet Drug/Medical',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (70,'%SEMEN%',512001,'AI Semen - P&I Trading',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (71,'%FODDER%',512001,'Fodder - P&I Trading',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (72,'%CATTLE FEED%',512001,'Cattle Feed - P&I Trading',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (73,'%MINERAL MIXTURE%',512001,'Mineral Mixture - P&I Trading',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (74,'%INSEMINATION%',512001,'AI Equipment - P&I Trading',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (75,'%MAIZE%',512001,'Seeds - P&I Trading',3);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (76,'%GOUDHARA%',512001,'Goudhara Shakthi - P&I Trading',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (77,'%LACTOMETER%',512001,'Lactometer - P&I Trading',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (78,'%BUTYROMETER%',512001,'Butyrometer - P&I Trading',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (79,'%MILK ANALYZER%',512001,'Milk Analyzer - P&I Trading',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (80,'%A.I. GUN%',512001,'AI Gun - P&I Trading',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (81,'%LIQUID NITROGEN%',512001,'LN2 - P&I Trading',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (82,'%NEPIER%',512001,'Fodder Seed - P&I Trading',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (83,'%LUCERNE%',512001,'Fodder - P&I Trading',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (84,'%COWPEA%',512001,'Fodder - P&I Trading',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (85,'%CALF STARTER%',512001,'Cattle Feed - P&I Trading',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (86,'%CALF GROWTH%',512001,'Cattle Feed - P&I Trading',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (87,'%VELVET BEANS%',512001,'Seeds - P&I Trading',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (88,'%NUGGE SEED%',512001,'Seeds - P&I Trading',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (89,'%NUTRI SAC%',512001,'Feed Supplement - P&I Trading',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (90,'%SAMRUDHI FEED%',512001,'Feed - P&I Trading',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (91,'%CHAFFCUTTER%',512001,'P&I Equipment',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (92,'%COW MAT%',512001,'P&I Equipment',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (93,'%MILKING MACHINE%',512001,'P&I Equipment',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (94,'%EARTH AUGER%',512001,'P&I Equipment',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (95,'%BMC%',512001,'BMC - P&I Trading',8);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (96,'%BULK MILK COOLER%',512001,'BMC - P&I Trading',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (97,'%WEIGHING SCALE%P&I%',512001,'P&I Weighing Scale',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (98,'%TRACTOR%',512001,'P&I Equipment',3);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (100,'%REGISTER%',512002,'Books - P&I Non-Trading',12);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (101,'%PASS BOOK%',512002,'Books - P&I Non-Trading',5);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (102,'%BYE LAW%',512002,'Books - P&I Non-Trading',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (103,'%BYE-LAW%',512002,'Books - P&I Non-Trading',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (104,'%RECEIPT BOOK%',512002,'Books - P&I Non-Trading',3);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (105,'%BILL PAD%',512002,'Books - P&I Non-Trading',5);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (106,'%CASE SHEET%',512002,'Books - P&I Non-Trading',3);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (107,'%VOUCHER BOOK%',512002,'Books - P&I Non-Trading',3);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (108,'%COUPON BOOK%',512002,'Books - P&I Non-Trading',3);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (109,'%COUPAN BOOK%',512002,'Books - P&I Non-Trading',3);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (110,'%MEMBERSHIP%',512002,'DCS Materials - Non-Trading',3);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (111,'%SHARE RECEIPT%',512002,'DCS Materials - Non-Trading',3);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (112,'%SHARE REGISTER%',512002,'DCS Materials - Non-Trading',3);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (113,'%DELIVERY NOTE%',512002,'Books - P&I Non-Trading',3);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (114,'%MPCS%CERTIFICATE%',512002,'DCS Materials - Non-Trading',3);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (115,'%EVP HANDBOOK%',512002,'Books - P&I Non-Trading',3);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (116,'%AGREEMENT FORMAT%',512002,'Books - P&I Non-Trading',3);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (117,'%LAMINATED PHOTO%',512002,'DCS Materials - Non-Trading',5);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (118,'%PRICE CHART%',512002,'DCS Materials - Non-Trading',3);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (119,'%FOAM BOARD%',512002,'DCS Materials - Non-Trading',5);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (120,'%EVM BOOKS%',512002,'Books - P&I Non-Trading',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (130,'%CRUCIBLE%',532005,'Lab Equipment',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (131,'%MEASURING CYLINDER%',532005,'Lab Equipment',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (132,'%PIPETTE%',532005,'Lab Equipment',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (133,'%FLASK%',532005,'Lab Equipment',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (134,'%PH ELECTRODE%',532005,'Lab Equipment',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (135,'%CONDUCTIVITY%METER%',532005,'Lab Equipment',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (136,'%CALIBRATION%',532005,'Lab Testing',2);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (137,'%SWAB%',532005,'Lab Testing',2);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (138,'%CUVETTE%',532005,'Lab Equipment',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (139,'%GLASS SQUEEZER%',532005,'Lab Equipment',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (140,'%REAGENT BOTTLE%',532005,'Lab Equipment',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (141,'%SAMPLE BOTTLE%',532005,'Lab Equipment',3);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (142,'%ACID BOTTLE%',532005,'Lab Equipment',2);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (143,'%FAT PAST SOLUTION%',532005,'Lab Chemical',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (144,'%FAT PLUS%',532005,'Lab Chemical',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (145,'%DESCALING SOLUTION%',532005,'Lab Chemical',2);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (146,'%LD POWDER%',532005,'Lab Chemical',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (147,'%LACTO DAILY%',532005,'Lab Chemical',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (148,'%LACTO WEEKLY%',532005,'Lab Chemical',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (149,'%CLEANING SOLUTION%',532005,'Lab Chemical',3);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (150,'%MILKOSCREEN%',532005,'Lab Chemical',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (151,'%SAAF KIT%',532005,'Lab Chemical',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (152,'%HI-MEDIA%',532005,'Lab Material',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (153,'%INDIFOSS%',532005,'Lab Equipment',2);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (154,'%HANNA INSTRUMENTS%',532005,'Lab Equipment',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (155,'%ANALYSIS CHARGE%',532005,'Lab Testing',2);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (160,'%BEARING%',513001,'General Consumables',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (161,'%GASKET%',513001,'General Consumables',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (162,'%O RING%',513001,'General Consumables',2);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (163,'%O-RING%',513001,'General Consumables',2);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (164,'%SEAL%',513001,'General Consumables',5);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (165,'%VALVE%',513001,'General Consumables',5);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (166,'%PUMP%',513001,'General Consumables',5);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (167,'%FILTER%',513001,'General Consumables',5);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (168,'%V BELT%',513001,'General Consumables',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (169,'%HOSE%',513001,'General Consumables',5);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (170,'%FUSE%',513001,'General Consumables',5);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (171,'%CABLE%',513001,'General Consumables',5);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (172,'%BOLT%',513001,'General Consumables',5);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (173,'%WRENCH%',513001,'General Consumables',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (174,'%SPANNER%',513001,'General Consumables',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (175,'%PLIER%',513001,'General Consumables',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (176,'%DRILL BIT%',513001,'General Consumables',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (177,'%GREASE%',513001,'General Consumables',3);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (178,'%LUBRICANT%',513001,'General Consumables',3);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (179,'%KLUBER%',513001,'General Consumables',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (180,'%SPARE%',513001,'General Consumables',8);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (181,'%PAINT%',513001,'General Consumables',5);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (182,'%EMULSION%',513001,'General Consumables',5);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (183,'%PVC%',513001,'General Consumables',7);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (184,'%CPVC%',513001,'General Consumables',5);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (185,'%ELBOW%',513001,'General Consumables',5);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (186,'%REDUCER%',513001,'General Consumables',5);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (187,'%CONNECTOR%',513001,'General Consumables',7);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (188,'%DIAPHRAGM%',513001,'General Consumables',3);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (189,'%PISTON%',513001,'General Consumables',3);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (190,'%SPROCKET%',513001,'General Consumables',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (191,'%CHAIN%',513001,'General Consumables',7);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (192,'%COUPLING%',513001,'General Consumables',3);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (193,'%TIMING PULLEY%',513001,'General Consumables',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (194,'%TIMING BELT%',513001,'General Consumables',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (195,'%RUBBER%',513001,'General Consumables',8);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (196,'%SOLVENT%CARTRIDGE%',513001,'General Consumables',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (197,'%RIBBON%CARTRIDGE%',513001,'General Consumables',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (198,'%SERVICE KIT%',513001,'General Consumables',2);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (199,'%ALLEN KEY%',513001,'General Consumables',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (200,'%HAND GLOVES%',513001,'Safety Consumables',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (201,'%GUM BOOT%',513001,'Safety Consumables',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (202,'%SANITIZER%',513001,'Cleaning Consumables',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (203,'%HAND WASH%',513001,'Cleaning Consumables',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (204,'%FIRE%EXTINGUISHER%',513001,'Safety Consumables',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (205,'%PHENYL%',513001,'Cleaning Consumables',2);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (206,'%DETERGENT%',513001,'Cleaning Consumables',3);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (207,'%CLEANING%',513001,'Cleaning Consumables',10);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (208,'%PROXIMITY SENSOR%',513001,'General Consumables',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (209,'%SOLENOID%',513001,'General Consumables',2);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (210,'%CONTACTOR%',513001,'Electrical Consumables',2);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (211,'%MCB%',513001,'Electrical Consumables',3);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (212,'%SWITCH%GEAR%',513001,'Electrical Consumables',3);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (213,'%COPPER LUG%',513001,'Electrical Consumables',2);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (214,'%COPPER TERMINAL%',513001,'Electrical Consumables',2);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (215,'%SAFETY RELAY%',513001,'Electrical Consumables',2);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (216,'%MOTOR%',513001,'General Consumables',8);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (217,'%SENSOR%',513001,'General Consumables',8);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (218,'%TRANSMITTER%',513001,'General Consumables',5);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (219,'%TUBE%',513001,'General Consumables',9);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (220,'%FLATS MS%',513001,'General Consumables',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (221,'%INK JET PRINTER%',513001,'General Consumables',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (222,'%STEEL TAP%',513001,'General Consumables',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (223,'%ROLLER%',513001,'General Consumables',5);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (224,'%HEATSINK%',513001,'General Consumables',3);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (225,'%NYLON%',513001,'General Consumables',8);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (226,'%INSULATOR%',513001,'Electrical Consumables',3);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (227,'%CONVEYOR BELT%',513001,'General Consumables',2);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (228,'%LOAD CELL%',513001,'General Consumables',2);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (229,'%CARTRIDGE%',513001,'General Consumables',8);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (230,'%REFILLING%',513001,'General Consumables',8);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (231,'%TONER%',513001,'General Consumables',5);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (232,'%DISPOSABLE%',513001,'General Consumables',5);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (233,'%WASHING SODA%',513001,'Cleaning Consumables',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (234,'%SODA ASH%',513001,'Cleaning Consumables',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (240,'%MAINTENANCE CONTRACT%',831001,'AMC General',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (241,'%AMC%',831001,'AMC General',2);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (242,'%BIENNIAL MAINTENANCE%',831001,'AMC General',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (243,'%ANNUAL MAINTENANCE%',831001,'AMC General',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (250,'%CONSULTANCY%',833002,'Professional Service',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (251,'%CONSULTANT%',833002,'Professional Service',2);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (252,'%PROFESSIONAL%',833002,'Professional Service',5);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (253,'%AUDIT%',833003,'Audit Fees',3);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (260,'%SERVICE CHARGES%',833002,'Professional Service',3);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (261,'%SERVICE & REPAIR%',532003,'Repair & Maintenance',2);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (262,'%SERVICE & MAINTENANCE%',532003,'Repair & Maintenance',2);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (263,'%REPAIR%',532003,'Repair & Maintenance',7);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (264,'%LABOUR CHARGES%',521001,'Contract Labour',3);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (265,'%LABOUR SUPPLY%',521001,'Contract Labour',3);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (266,'%CONTRACT LABOUR%',521001,'Contract Labour',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (267,'%MAN POWER%',521001,'Contract Labour',3);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (270,'%WATERPROOF%',532001,'Building Maintenance',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (271,'%FLOORING%',532001,'Building Maintenance',2);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (272,'%PARTITION%',532001,'Building Maintenance',3);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (273,'%PUF PANEL%',532001,'Building Maintenance',2);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (274,'%BOREWELL%',532001,'Building Maintenance',2);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (275,'%HUME PIPE%',532001,'Building Maintenance',2);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (276,'%CIVIL%',532001,'Building Maintenance',8);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (280,'%PEST CONTROL%',532002,'Pest Control',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (281,'%POLLUTION CONTROL%',532002,'Pollution Control',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (282,'%DISINFESTATION%',532002,'Pest Control',2);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (283,'%RODENT CONTROL%',532002,'Pest Control',2);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (284,'%CFO FROM KSPCB%',532002,'Pollution Control',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (290,'%LED%LIGHT%',532008,'Electrical',3);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (291,'%LED%LAMP%',532008,'Electrical',3);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (292,'%STREET LIGHT%',532008,'Electrical',2);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (293,'%POWER PACK%',513001,'Electrical Consumable',3);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (295,'%RO MEMBRANE%',532009,'Water Treatment',2);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (296,'%RO WATER%',532009,'Water Treatment',3);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (297,'%WATER PURIFIER%',532009,'Water Treatment',2);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (300,'%INSURANCE%',532004,'Insurance',5);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (310,'%TRANSPORT%',531003,'Transportation',8);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (311,'%FREIGHT%',531001,'Freight',5);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (312,'%BANGALURU TO%',531003,'Transportation',3);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (320,'%ADVERTISEMENT%',861002,'Promotional Sales',2);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (321,'%PUBLICITY%',861002,'Promotional Sales',3);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (322,'%PROMOTION%',861002,'Promotional Sales',5);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (323,'%SIGN BOARD%',861005,'Marketing Expenses',3);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (324,'%SUN BOARD%',861005,'Marketing Expenses',3);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (325,'%WALL CALENDAR%',861005,'Marketing Expenses',3);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (326,'%LED WALL:0',861005,'Marketing Expenses',2);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (330,'%ENVELOPE%',831004,'Office Expenses',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (331,'%STAMP PAD%',831004,'Office Expenses',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (332,'%GUM BOTTLE%',831004,'Office Expenses',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (333,'%HIGHLIGHT%',831004,'Office Expenses',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (334,'%RUBBER SEAL%',831004,'Office Expenses',3);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (335,'%PAYMENT SEAL%',831004,'Office Expenses',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (336,'%SCRIBBLING PAD%',831004,'Office Expenses',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (337,'%HANSA FILE%',831004,'Office Expenses',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (338,'%LOCK%',831004,'Office Expenses',8);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (340,'%DESKTOP COMPUTER%',100106,'Computers',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (341,'%LAPTOP%',100106,'Computers',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (342,'%IPAD%',100106,'Computers',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (343,'%MOBILE PHONE%',100113,'Office Equipment',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (344,'%TAB%',100113,'Office Equipment',9);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (350,'%EXECUTIVE TABLE%',100108,'Furniture',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (351,'%VISITOR CHAIR%',100108,'Furniture',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (352,'%WAITING CHAIR%',100108,'Furniture',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (353,'%ALMIRAH%',100108,'Furniture',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (360,'%TRACTOR%',100116,'Vehicles',5);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (370,'%HOMOGENIZER%',100114,'Plant & Machinery',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (371,'%SEPARATOR%',100114,'Plant & Machinery',3);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (372,'%EVAPORATOR%',100114,'Plant & Machinery',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (373,'%CIP%PUMP%',100114,'Plant & Machinery',2);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (374,'%COMPRESSOR%',100114,'Plant & Machinery',3);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (375,'%AIR DRYER%',100114,'Plant & Machinery',3);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (376,'%PLC%',100114,'Plant & Machinery',5);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (377,'%AUTOMATION%',100114,'Plant & Machinery',5);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (378,'%VACUUM HOPPER%',100114,'Plant & Machinery',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (379,'%VFD%',100114,'Plant & Machinery',5);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (380,'%WEIGHING SCALE%',100113,'Office Equipment',5);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (381,'%WEIGHING BALANCE%',100113,'Office Equipment',5);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (382,'%DEAD WEIGHT%',100113,'Office Equipment',3);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (383,'%PROJECTOR%',100113,'Office Equipment',2);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (384,'%UPS%',100113,'Office Equipment',7);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (385,'%NVR%',100113,'Office Equipment',3);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (386,'%CAMERA%',100113,'Office Equipment',5);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (390,'%PHOTOGRAPHY%',861005,'Marketing Expenses',2);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (395,'%KADAI%',821001,'Canteen Equipment',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (396,'%FRY STRAINER%',821001,'Canteen Equipment',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (397,'%CANTEEN%',821001,'Canteen Expenses',3);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (398,'%FLY CATCHER%',513001,'General Consumables',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (400,'%SECURITY SERVICE%',831006,'Security Charges',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (410,'%TELEPHONE%',831007,'Telephone/Internet',3);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (411,'%INTERNET%',831007,'Telephone/Internet',3);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (420,'%VEHICLE TAX%',831011,'Vehicle Expenses',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (421,'%VEHICLE INSURANCE%',831011,'Vehicle Expenses',1);
Insert into APPS.MAPPING_ITEM_KEYWORD_ACCOUNT (KEYWORD_ID,KEYWORD_PATTERN,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION,PRIORITY) values (422,'%VEHICLE%REPAIR%',831011,'Vehicle Expenses',2);
--------------------------------------------------------
--  DDL for Index MAPPING_ITEM_KEYWORD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS"."MAPPING_ITEM_KEYWORD_PK" ON "APPS"."MAPPING_ITEM_KEYWORD_ACCOUNT" ("KEYWORD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  Constraints for Table MAPPING_ITEM_KEYWORD_ACCOUNT
--------------------------------------------------------

  ALTER TABLE "APPS"."MAPPING_ITEM_KEYWORD_ACCOUNT" MODIFY ("KEYWORD_ID" NOT NULL ENABLE);
  ALTER TABLE "APPS"."MAPPING_ITEM_KEYWORD_ACCOUNT" MODIFY ("KEYWORD_PATTERN" NOT NULL ENABLE);
  ALTER TABLE "APPS"."MAPPING_ITEM_KEYWORD_ACCOUNT" MODIFY ("NEW_ACCOUNT_FLEX_VALUE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."MAPPING_ITEM_KEYWORD_ACCOUNT" ADD CONSTRAINT "MAPPING_ITEM_KEYWORD_PK" PRIMARY KEY ("KEYWORD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA"  ENABLE;
