--------------------------------------------------------
--  File created - Wednesday-May-06-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MAPPING_DEPARTMENT_SEGMENT
--------------------------------------------------------

  CREATE TABLE "APPS"."MAPPING_DEPARTMENT_SEGMENT" 
   (	"OLD_DEPARTMENT_FLEX_VALUE" VARCHAR2(30 BYTE), 
	"NEW_DEPARTMENT_FLEX_VALUE" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
REM INSERTING into APPS.MAPPING_DEPARTMENT_SEGMENT
SET DEFINE OFF;
Insert into APPS.MAPPING_DEPARTMENT_SEGMENT (OLD_DEPARTMENT_FLEX_VALUE,NEW_DEPARTMENT_FLEX_VALUE) values ('29000','BEN11');
Insert into APPS.MAPPING_DEPARTMENT_SEGMENT (OLD_DEPARTMENT_FLEX_VALUE,NEW_DEPARTMENT_FLEX_VALUE) values ('31000','BAD07');
Insert into APPS.MAPPING_DEPARTMENT_SEGMENT (OLD_DEPARTMENT_FLEX_VALUE,NEW_DEPARTMENT_FLEX_VALUE) values ('30100','BAD07');
Insert into APPS.MAPPING_DEPARTMENT_SEGMENT (OLD_DEPARTMENT_FLEX_VALUE,NEW_DEPARTMENT_FLEX_VALUE) values ('20200','BEN02');
Insert into APPS.MAPPING_DEPARTMENT_SEGMENT (OLD_DEPARTMENT_FLEX_VALUE,NEW_DEPARTMENT_FLEX_VALUE) values ('13003','BAD05');
Insert into APPS.MAPPING_DEPARTMENT_SEGMENT (OLD_DEPARTMENT_FLEX_VALUE,NEW_DEPARTMENT_FLEX_VALUE) values ('40001','BPR01');
Insert into APPS.MAPPING_DEPARTMENT_SEGMENT (OLD_DEPARTMENT_FLEX_VALUE,NEW_DEPARTMENT_FLEX_VALUE) values ('45000','BPR01');
Insert into APPS.MAPPING_DEPARTMENT_SEGMENT (OLD_DEPARTMENT_FLEX_VALUE,NEW_DEPARTMENT_FLEX_VALUE) values ('45001','BPR02');
Insert into APPS.MAPPING_DEPARTMENT_SEGMENT (OLD_DEPARTMENT_FLEX_VALUE,NEW_DEPARTMENT_FLEX_VALUE) values ('45002','BPR03');
Insert into APPS.MAPPING_DEPARTMENT_SEGMENT (OLD_DEPARTMENT_FLEX_VALUE,NEW_DEPARTMENT_FLEX_VALUE) values ('45003','BPR04');
Insert into APPS.MAPPING_DEPARTMENT_SEGMENT (OLD_DEPARTMENT_FLEX_VALUE,NEW_DEPARTMENT_FLEX_VALUE) values ('45004','BPR05');
Insert into APPS.MAPPING_DEPARTMENT_SEGMENT (OLD_DEPARTMENT_FLEX_VALUE,NEW_DEPARTMENT_FLEX_VALUE) values ('45005','BPR06');
Insert into APPS.MAPPING_DEPARTMENT_SEGMENT (OLD_DEPARTMENT_FLEX_VALUE,NEW_DEPARTMENT_FLEX_VALUE) values ('45006','BPR07');
Insert into APPS.MAPPING_DEPARTMENT_SEGMENT (OLD_DEPARTMENT_FLEX_VALUE,NEW_DEPARTMENT_FLEX_VALUE) values ('45007','BAD05');
Insert into APPS.MAPPING_DEPARTMENT_SEGMENT (OLD_DEPARTMENT_FLEX_VALUE,NEW_DEPARTMENT_FLEX_VALUE) values ('50001','BMK06');
Insert into APPS.MAPPING_DEPARTMENT_SEGMENT (OLD_DEPARTMENT_FLEX_VALUE,NEW_DEPARTMENT_FLEX_VALUE) values ('50002','BMK06');
Insert into APPS.MAPPING_DEPARTMENT_SEGMENT (OLD_DEPARTMENT_FLEX_VALUE,NEW_DEPARTMENT_FLEX_VALUE) values ('50003','BMK06');
Insert into APPS.MAPPING_DEPARTMENT_SEGMENT (OLD_DEPARTMENT_FLEX_VALUE,NEW_DEPARTMENT_FLEX_VALUE) values ('60050','BPI01');
Insert into APPS.MAPPING_DEPARTMENT_SEGMENT (OLD_DEPARTMENT_FLEX_VALUE,NEW_DEPARTMENT_FLEX_VALUE) values ('80050','BQC01');
Insert into APPS.MAPPING_DEPARTMENT_SEGMENT (OLD_DEPARTMENT_FLEX_VALUE,NEW_DEPARTMENT_FLEX_VALUE) values ('90050','BAD08');
Insert into APPS.MAPPING_DEPARTMENT_SEGMENT (OLD_DEPARTMENT_FLEX_VALUE,NEW_DEPARTMENT_FLEX_VALUE) values ('00005','BPI10');
Insert into APPS.MAPPING_DEPARTMENT_SEGMENT (OLD_DEPARTMENT_FLEX_VALUE,NEW_DEPARTMENT_FLEX_VALUE) values ('00011','BCC01');
Insert into APPS.MAPPING_DEPARTMENT_SEGMENT (OLD_DEPARTMENT_FLEX_VALUE,NEW_DEPARTMENT_FLEX_VALUE) values ('00012','BCC03');
Insert into APPS.MAPPING_DEPARTMENT_SEGMENT (OLD_DEPARTMENT_FLEX_VALUE,NEW_DEPARTMENT_FLEX_VALUE) values ('00013','BCC04');
Insert into APPS.MAPPING_DEPARTMENT_SEGMENT (OLD_DEPARTMENT_FLEX_VALUE,NEW_DEPARTMENT_FLEX_VALUE) values ('00014','BCC06');
Insert into APPS.MAPPING_DEPARTMENT_SEGMENT (OLD_DEPARTMENT_FLEX_VALUE,NEW_DEPARTMENT_FLEX_VALUE) values ('00015','BCC02');
Insert into APPS.MAPPING_DEPARTMENT_SEGMENT (OLD_DEPARTMENT_FLEX_VALUE,NEW_DEPARTMENT_FLEX_VALUE) values ('00016','BCC05');
Insert into APPS.MAPPING_DEPARTMENT_SEGMENT (OLD_DEPARTMENT_FLEX_VALUE,NEW_DEPARTMENT_FLEX_VALUE) values ('00017','BCC07');
Insert into APPS.MAPPING_DEPARTMENT_SEGMENT (OLD_DEPARTMENT_FLEX_VALUE,NEW_DEPARTMENT_FLEX_VALUE) values ('00051','BCO01');
Insert into APPS.MAPPING_DEPARTMENT_SEGMENT (OLD_DEPARTMENT_FLEX_VALUE,NEW_DEPARTMENT_FLEX_VALUE) values ('00052','BCO02');
Insert into APPS.MAPPING_DEPARTMENT_SEGMENT (OLD_DEPARTMENT_FLEX_VALUE,NEW_DEPARTMENT_FLEX_VALUE) values ('00053','BCO03');
Insert into APPS.MAPPING_DEPARTMENT_SEGMENT (OLD_DEPARTMENT_FLEX_VALUE,NEW_DEPARTMENT_FLEX_VALUE) values ('00054','BCO04');
Insert into APPS.MAPPING_DEPARTMENT_SEGMENT (OLD_DEPARTMENT_FLEX_VALUE,NEW_DEPARTMENT_FLEX_VALUE) values ('00055','BCO05');
Insert into APPS.MAPPING_DEPARTMENT_SEGMENT (OLD_DEPARTMENT_FLEX_VALUE,NEW_DEPARTMENT_FLEX_VALUE) values ('00056','BCO06');
Insert into APPS.MAPPING_DEPARTMENT_SEGMENT (OLD_DEPARTMENT_FLEX_VALUE,NEW_DEPARTMENT_FLEX_VALUE) values ('00057','BCO07');
Insert into APPS.MAPPING_DEPARTMENT_SEGMENT (OLD_DEPARTMENT_FLEX_VALUE,NEW_DEPARTMENT_FLEX_VALUE) values ('00058','BCO08');
Insert into APPS.MAPPING_DEPARTMENT_SEGMENT (OLD_DEPARTMENT_FLEX_VALUE,NEW_DEPARTMENT_FLEX_VALUE) values ('00059','BCO09');
Insert into APPS.MAPPING_DEPARTMENT_SEGMENT (OLD_DEPARTMENT_FLEX_VALUE,NEW_DEPARTMENT_FLEX_VALUE) values ('00060','BCO10');
Insert into APPS.MAPPING_DEPARTMENT_SEGMENT (OLD_DEPARTMENT_FLEX_VALUE,NEW_DEPARTMENT_FLEX_VALUE) values ('00061','BCO11');
Insert into APPS.MAPPING_DEPARTMENT_SEGMENT (OLD_DEPARTMENT_FLEX_VALUE,NEW_DEPARTMENT_FLEX_VALUE) values ('00062','BCO12');
Insert into APPS.MAPPING_DEPARTMENT_SEGMENT (OLD_DEPARTMENT_FLEX_VALUE,NEW_DEPARTMENT_FLEX_VALUE) values ('00064','BCO13');
Insert into APPS.MAPPING_DEPARTMENT_SEGMENT (OLD_DEPARTMENT_FLEX_VALUE,NEW_DEPARTMENT_FLEX_VALUE) values ('00065','BCO14');
Insert into APPS.MAPPING_DEPARTMENT_SEGMENT (OLD_DEPARTMENT_FLEX_VALUE,NEW_DEPARTMENT_FLEX_VALUE) values ('10100','BAD01');
Insert into APPS.MAPPING_DEPARTMENT_SEGMENT (OLD_DEPARTMENT_FLEX_VALUE,NEW_DEPARTMENT_FLEX_VALUE) values ('11000','BAD03');
Insert into APPS.MAPPING_DEPARTMENT_SEGMENT (OLD_DEPARTMENT_FLEX_VALUE,NEW_DEPARTMENT_FLEX_VALUE) values ('12000','BAD04');
Insert into APPS.MAPPING_DEPARTMENT_SEGMENT (OLD_DEPARTMENT_FLEX_VALUE,NEW_DEPARTMENT_FLEX_VALUE) values ('13000','BAD05');
Insert into APPS.MAPPING_DEPARTMENT_SEGMENT (OLD_DEPARTMENT_FLEX_VALUE,NEW_DEPARTMENT_FLEX_VALUE) values ('13002','BAD05');
Insert into APPS.MAPPING_DEPARTMENT_SEGMENT (OLD_DEPARTMENT_FLEX_VALUE,NEW_DEPARTMENT_FLEX_VALUE) values ('13004','BAD05');
Insert into APPS.MAPPING_DEPARTMENT_SEGMENT (OLD_DEPARTMENT_FLEX_VALUE,NEW_DEPARTMENT_FLEX_VALUE) values ('14000','BAD06');
Insert into APPS.MAPPING_DEPARTMENT_SEGMENT (OLD_DEPARTMENT_FLEX_VALUE,NEW_DEPARTMENT_FLEX_VALUE) values ('20100','BEN01');
Insert into APPS.MAPPING_DEPARTMENT_SEGMENT (OLD_DEPARTMENT_FLEX_VALUE,NEW_DEPARTMENT_FLEX_VALUE) values ('21000','BEN03');
Insert into APPS.MAPPING_DEPARTMENT_SEGMENT (OLD_DEPARTMENT_FLEX_VALUE,NEW_DEPARTMENT_FLEX_VALUE) values ('22000','BEN04');
Insert into APPS.MAPPING_DEPARTMENT_SEGMENT (OLD_DEPARTMENT_FLEX_VALUE,NEW_DEPARTMENT_FLEX_VALUE) values ('23000','BEN05');
Insert into APPS.MAPPING_DEPARTMENT_SEGMENT (OLD_DEPARTMENT_FLEX_VALUE,NEW_DEPARTMENT_FLEX_VALUE) values ('24000','BEN06');
Insert into APPS.MAPPING_DEPARTMENT_SEGMENT (OLD_DEPARTMENT_FLEX_VALUE,NEW_DEPARTMENT_FLEX_VALUE) values ('25000','BEN07');
Insert into APPS.MAPPING_DEPARTMENT_SEGMENT (OLD_DEPARTMENT_FLEX_VALUE,NEW_DEPARTMENT_FLEX_VALUE) values ('26000','BEN08');
Insert into APPS.MAPPING_DEPARTMENT_SEGMENT (OLD_DEPARTMENT_FLEX_VALUE,NEW_DEPARTMENT_FLEX_VALUE) values ('27000','BEN09');
Insert into APPS.MAPPING_DEPARTMENT_SEGMENT (OLD_DEPARTMENT_FLEX_VALUE,NEW_DEPARTMENT_FLEX_VALUE) values ('28000','BEN10');
--------------------------------------------------------
--  DDL for Index SYS_C00435522
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS"."SYS_C00435522" ON "APPS"."MAPPING_DEPARTMENT_SEGMENT" ("OLD_DEPARTMENT_FLEX_VALUE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  Constraints for Table MAPPING_DEPARTMENT_SEGMENT
--------------------------------------------------------

  ALTER TABLE "APPS"."MAPPING_DEPARTMENT_SEGMENT" ADD PRIMARY KEY ("OLD_DEPARTMENT_FLEX_VALUE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA"  ENABLE;
