--------------------------------------------------------
--  File created - Wednesday-May-06-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MAPPING_PRODUCT_PREFIX_ACCOUNT
--------------------------------------------------------

  CREATE TABLE "APPS"."MAPPING_PRODUCT_PREFIX_ACCOUNT" 
   (	"PRODUCT_PREFIX" VARCHAR2(4 BYTE), 
	"NEW_ACCOUNT_FLEX_VALUE" NUMBER(6,0), 
	"ACCOUNT_DESCRIPTION" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
REM INSERTING into APPS.MAPPING_PRODUCT_PREFIX_ACCOUNT
SET DEFINE OFF;
Insert into APPS.MAPPING_PRODUCT_PREFIX_ACCOUNT (PRODUCT_PREFIX,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION) values ('BM',121001,'Butter Milk → Finished Products');
Insert into APPS.MAPPING_PRODUCT_PREFIX_ACCOUNT (PRODUCT_PREFIX,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION) values ('BU',121001,'Butter → Finished Products');
Insert into APPS.MAPPING_PRODUCT_PREFIX_ACCOUNT (PRODUCT_PREFIX,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION) values ('CH',121001,'Cheese → Finished Products');
Insert into APPS.MAPPING_PRODUCT_PREFIX_ACCOUNT (PRODUCT_PREFIX,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION) values ('CR',121001,'Cream → Finished Products');
Insert into APPS.MAPPING_PRODUCT_PREFIX_ACCOUNT (PRODUCT_PREFIX,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION) values ('CU',121001,'Curd → Finished Products');
Insert into APPS.MAPPING_PRODUCT_PREFIX_ACCOUNT (PRODUCT_PREFIX,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION) values ('FM',121001,'Flavoured Milk → Finished Products');
Insert into APPS.MAPPING_PRODUCT_PREFIX_ACCOUNT (PRODUCT_PREFIX,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION) values ('GH',121001,'Ghee → Finished Products');
Insert into APPS.MAPPING_PRODUCT_PREFIX_ACCOUNT (PRODUCT_PREFIX,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION) values ('KH',121001,'Khova → Finished Products');
Insert into APPS.MAPPING_PRODUCT_PREFIX_ACCOUNT (PRODUCT_PREFIX,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION) values ('MI',121001,'Milk → Finished Products');
Insert into APPS.MAPPING_PRODUCT_PREFIX_ACCOUNT (PRODUCT_PREFIX,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION) values ('MP',121001,'Mysore Pak → Finished Products');
Insert into APPS.MAPPING_PRODUCT_PREFIX_ACCOUNT (PRODUCT_PREFIX,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION) values ('NM',121001,'Nandini Products → Finished Products');
Insert into APPS.MAPPING_PRODUCT_PREFIX_ACCOUNT (PRODUCT_PREFIX,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION) values ('PD',121001,'Peda → Finished Products');
Insert into APPS.MAPPING_PRODUCT_PREFIX_ACCOUNT (PRODUCT_PREFIX,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION) values ('PN',121001,'Paneer → Finished Products');
Insert into APPS.MAPPING_PRODUCT_PREFIX_ACCOUNT (PRODUCT_PREFIX,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION) values ('SL',121001,'Sweet Lassi → Finished Products');
Insert into APPS.MAPPING_PRODUCT_PREFIX_ACCOUNT (PRODUCT_PREFIX,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION) values ('SP',121001,'SMP → Finished Products');
Insert into APPS.MAPPING_PRODUCT_PREFIX_ACCOUNT (PRODUCT_PREFIX,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION) values ('UH',121001,'UHT Crate Products → Finished Products');
Insert into APPS.MAPPING_PRODUCT_PREFIX_ACCOUNT (PRODUCT_PREFIX,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION) values ('UM',121001,'UHT Milk → Finished Products');
Insert into APPS.MAPPING_PRODUCT_PREFIX_ACCOUNT (PRODUCT_PREFIX,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION) values ('WH',121001,'Whey Powder → Finished Products');
Insert into APPS.MAPPING_PRODUCT_PREFIX_ACCOUNT (PRODUCT_PREFIX,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION) values ('WP',121001,'Whole Milk Powder → Finished Products');
Insert into APPS.MAPPING_PRODUCT_PREFIX_ACCOUNT (PRODUCT_PREFIX,NEW_ACCOUNT_FLEX_VALUE,ACCOUNT_DESCRIPTION) values ('PI',122001,'P&I Items → Trading P&I Stock');
--------------------------------------------------------
--  DDL for Index MAPPING_PROD_PREFIX_ACCT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS"."MAPPING_PROD_PREFIX_ACCT_PK" ON "APPS"."MAPPING_PRODUCT_PREFIX_ACCOUNT" ("PRODUCT_PREFIX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  Constraints for Table MAPPING_PRODUCT_PREFIX_ACCOUNT
--------------------------------------------------------

  ALTER TABLE "APPS"."MAPPING_PRODUCT_PREFIX_ACCOUNT" MODIFY ("PRODUCT_PREFIX" NOT NULL ENABLE);
  ALTER TABLE "APPS"."MAPPING_PRODUCT_PREFIX_ACCOUNT" MODIFY ("NEW_ACCOUNT_FLEX_VALUE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."MAPPING_PRODUCT_PREFIX_ACCOUNT" ADD CONSTRAINT "MAPPING_PROD_PREFIX_ACCT_PK" PRIMARY KEY ("PRODUCT_PREFIX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA"  ENABLE;
