--------------------------------------------------------
--  File created - Wednesday-May-06-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MAPPING_DIVISION_SEGMENT
--------------------------------------------------------

  CREATE TABLE "APPS"."MAPPING_DIVISION_SEGMENT" 
   (	"ORGANIZATION_ID" NUMBER(10,0), 
	"DIVISION_CODE" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
REM INSERTING into APPS.MAPPING_DIVISION_SEGMENT
SET DEFINE OFF;
Insert into APPS.MAPPING_DIVISION_SEGMENT (ORGANIZATION_ID,DIVISION_CODE) values (171,'01');
Insert into APPS.MAPPING_DIVISION_SEGMENT (ORGANIZATION_ID,DIVISION_CODE) values (169,'02');
Insert into APPS.MAPPING_DIVISION_SEGMENT (ORGANIZATION_ID,DIVISION_CODE) values (170,'03');
--------------------------------------------------------
--  DDL for Index SYS_C00435518
--------------------------------------------------------

  CREATE UNIQUE INDEX "APPS"."SYS_C00435518" ON "APPS"."MAPPING_DIVISION_SEGMENT" ("ORGANIZATION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA" ;
--------------------------------------------------------
--  Constraints for Table MAPPING_DIVISION_SEGMENT
--------------------------------------------------------

  ALTER TABLE "APPS"."MAPPING_DIVISION_SEGMENT" MODIFY ("ORGANIZATION_ID" NOT NULL ENABLE);
  ALTER TABLE "APPS"."MAPPING_DIVISION_SEGMENT" MODIFY ("DIVISION_CODE" NOT NULL ENABLE);
  ALTER TABLE "APPS"."MAPPING_DIVISION_SEGMENT" ADD PRIMARY KEY ("ORGANIZATION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "APPS_TS_TX_DATA"  ENABLE;
